import { useCallback, useEffect, useMemo, useRef, useState, type CSSProperties } from "react";
import { analyzePattern, cellsForSide, curvePath, DIRS, HEX, keyOf, PATTERNS, Pattern, PatternGeometry, shuffle, signature, Tile } from "./game";
import "./globals.css";

type Placed = Tile;
type Preview = { cell:string; tileId:number; rotation:number };
type Component = { nodes:string[]; letters:string[]; closed:boolean; dead:boolean; touched:boolean; valid:boolean; words:string[] };
type Analysis = { components:Component[]; nodeStatus:Record<string,"affected"|"closed"|"invalid"|"dead">; valid:boolean; closed:Component[] };
type HistoryItem = { turn:number; words:string[]; wordPoints:number[]; points:number };
type WordColors = { one:string; two:string; three:string; four:string; five:string; six:string; sevenPlus:string };
type Theme = { id:string; name:string; surface:string; panel:string; tile:string; line:string; accent:string; void:string; words:WordColors };

const FALLBACK_FREQ="EEEEEEEEEEEEAAAAAAAAAIIIIIIIIIOOOOOOOONNNNNNRRRRRRTTTTTTLLLLSSSSUUUUDDDDGGGBBCCMMPPFFHHVVWWYYKJXQZ";
const SCRABBLE_COUNTS:Record<string,number>={A:9,B:2,C:2,D:4,E:12,F:2,G:3,H:2,I:9,J:1,K:1,L:4,M:2,N:6,O:8,P:2,Q:1,R:6,S:4,T:6,U:4,V:2,W:2,X:1,Y:2,Z:1};
const SHORT_WORDS=["A","I","AA","AB","AD","AE","AG","AH","AI","AL","AM","AN","AR","AS","AT","AW","AX","AY","BA","BE","BI","BO","BY","DA","DE","DO","ED","EF","EH","EL","EM","EN","ER","ES","ET","EW","EX","FA","FE","GI","GO","GU","HA","HE","HI","HM","HO","ID","IF","IN","IO","IS","IT","JA","JO","KA","KI","KO","KY","LA","LI","LO","MA","ME","MI","MM","MO","MU","MY","NA","NE","NG","NI","NO","NU","OD","OE","OF","OH","OI","OM","ON","OP","OR","OS","OU","OW","OX","OY","PA","PE","PI","PO","QI","RE","SH","SI","SO","TA","TE","TI","TO","UH","UM","UN","UP","US","UT","WE","WO","XI","XU","YA","YE","YO","ZA"];
const THEMES:Theme[]=[
  {id:"talavera",name:"Talavera Courtyard",surface:"#f1eadc",panel:"#e7ddcb",tile:"#fff8e8",line:"#b65b3d",accent:"#2f6390",void:"#d8d0c2",words:{one:"#8aa9a1",two:"#2a7f7a",three:"#d8a51d",four:"#c9543f",five:"#608449",six:"#d48642",sevenPlus:"#376b85"}},
  {id:"iznik",name:"İznik Evening",surface:"#eeeae3",panel:"#e0e4e7",tile:"#fffaf0",line:"#304f82",accent:"#b6484f",void:"#d7d9dc",words:{one:"#8a9eb5",two:"#2d8c91",three:"#365c9a",four:"#705083",five:"#b6484f",six:"#587d9d",sevenPlus:"#80627f"}},
  {id:"mediterranean",name:"Mediterranean Grove",surface:"#eee9df",panel:"#e3ddcf",tile:"#faf6eb",line:"#626b50",accent:"#a54d3d",void:"#d5d0c5",words:{one:"#a3a58e",two:"#77804e",three:"#c2763f",four:"#a54d3d",five:"#60777a",six:"#a98251",sevenPlus:"#875b50"}},
  {id:"castilian",name:"Castilian Sky",surface:"#edf0ee",panel:"#e0e6e6",tile:"#fcfdfb",line:"#5e568c",accent:"#c99b18",void:"#dce1e1",words:{one:"#8baaa5",two:"#d9b633",three:"#27928e",four:"#6d9a4b",five:"#d46a52",six:"#6486a7",sevenPlus:"#82639a"}},
  {id:"zellige",name:"Zellige Garden",surface:"#eee9dc",panel:"#e4dccb",tile:"#fff9e9",line:"#376b5a",accent:"#b47a25",void:"#d7d0c0",words:{one:"#83a49b",two:"#238b88",three:"#386a9a",four:"#d0a23a",five:"#a44f42",six:"#55805d",sevenPlus:"#665b8c"}},
];
const parsePairs=(value:string)=>{const out:[number,number][]=[];for(const part of value.split(",")){const m=part.trim().match(/^([1-6])\s*[-–:]\s*([1-6])$/);if(!m||m[1]===m[2])return null;out.push([+m[1],+m[2]]);}return out;};

function TileFace({tile,pattern,geometry,status={},fills={},hidden={},preview=false}:{tile:Tile;pattern:Pattern;geometry:PatternGeometry;status?:Record<number,string>;fills?:Record<number,string>;hidden?:Record<number,boolean>;preview?:boolean}){
  return <svg width="100" height="100" viewBox="0 0 100 100" className={preview?"tile-svg preview":"tile-svg"} aria-hidden="true">
    <polygon points={HEX.map(p=>p.join(",")).join(" ")} className="tile-paper" />
    <g transform={`rotate(${tile.rotation*60} 50 50)`}>
      {geometry.regions.map((region)=><path key={region.id} d={region.mask} className={`region-fill ${status[region.id]||""}`} style={fills[region.id]?{fill:fills[region.id]}:undefined} />)}
      {pattern.pairs.map((pair,i)=><path key={i} d={curvePath(pair)} className="wall" />)}
      {geometry.regions.map((region)=>tile.letters[region.id]&&!hidden[region.id]&&<text key={`l${region.id}`} x={region.cx} y={region.cy+4.2} transform={preview?undefined:`rotate(${-tile.rotation*60} ${region.cx} ${region.cy})`} className="letter">{tile.letters[region.id]}</text>)}
    </g>
  </svg>;
}

export default function App(){
  const internal=false;
  const [tab,setTab]=useState<"play"|"lab">("play");
  const [patterns,setPatterns]=useState<Pattern[]>(PATTERNS);
  const [deckSize,setDeckSize]=useState(50);
  const [boardSide,setBoardSide]=useState(4);
  const [startingHand,setStartingHand]=useState(3);
  const [letterSpawnRate,setLetterSpawnRate]=useState(60);
  const [wordColors,setWordColors]=useState<WordColors>(THEMES[4].words);
  const [lineColor,setLineColor]=useState(THEMES[4].line);
  const [voidColor,setVoidColor]=useState(THEMES[4].void);
  const [themeId,setThemeId]=useState("zellige");
  const [surfaceColor,setSurfaceColor]=useState(THEMES[4].surface);
  const [panelColor,setPanelColor]=useState(THEMES[4].panel);
  const [tileColor,setTileColor]=useState(THEMES[4].tile);
  const [accentColor,setAccentColor]=useState(THEMES[4].accent);
  const [configDirty,setConfigDirty]=useState(false);
  const [configLoaded,setConfigLoaded]=useState(false);
  const [dictionaryLoaded,setDictionaryLoaded]=useState(false);
  const geometries=useMemo(()=>Object.fromEntries(patterns.map(p=>[p.id,analyzePattern(p)])),[patterns]);
  const cells=useMemo(()=>cellsForSide(boardSide),[boardSide]);
  const boardKeys=useMemo(()=>new Set(cells.map(({q,r})=>keyOf(q,r))),[cells]);
  const [words,setWords]=useState<string[]>([]);
  const [exact,setExact]=useState<Map<string,string[]>>(new Map());
  const [letterPool,setLetterPool]=useState(FALLBACK_FREQ);
  const [board,setBoard]=useState<Record<string,Placed>>({});
  const [deck,setDeck]=useState<Tile[]>([]);
  const [hand,setHand]=useState<Tile[]>([]);
  const [handSlots,setHandSlots]=useState<Record<number,number>>({});
  const [handSlotCount,setHandSlotCount]=useState(0);
  const [newId,setNewId]=useState<number|null>(null);
  const [selectedId,setSelectedId]=useState<number|null>(null);
  const [draggingId,setDraggingId]=useState<number|null>(null);
  const [dragVisual,setDragVisual]=useState<{tileId:number;x:number;y:number;size:number}|null>(null);
  const [preview,setPreview]=useState<Preview|null>(null);
  const [score,setScore]=useState(0);
  const [,setDestroyedCount]=useState(0);
  const [turn,setTurn]=useState(1);
  const [history,setHistory]=useState<HistoryItem[]>([]);
  const [closedNodes,setClosedNodes]=useState<Record<string,number>>({});
  const [warn,setWarn]=useState(false);
  const [finder,setFinder]=useState(true);
  const [chooseWord,setChooseWord]=useState(false);
  const [showInstructions,setShowInstructions]=useState(false);
  const [flash,setFlash]=useState(false);
  const [pending,setPending]=useState<Component[]|null>(null);
  const [entries,setEntries]=useState<string[]>([]);
  const [gameOver,setGameOver]=useState(false);
  const boardSvgRef=useRef<SVGSVGElement|null>(null);
  const dragGhostRef=useRef<HTMLElement|null>(null);
  const dropAcceptedRef=useRef(false);

  useEffect(()=>{fetch(`${import.meta.env.BASE_URL}words.txt`).then(r=>r.text()).then(text=>{const longWords=text.split(/\s+/).filter(w=>w.length>=3),list=[...SHORT_WORDS,...longWords];setWords(list);const map=new Map<string,string[]>(),counts:Record<string,number>={};for(const word of list){const sig=signature(word);const arr=map.get(sig)||[];if(arr.length<30)arr.push(word);map.set(sig,arr);}for(const word of longWords)for(const c of word)counts[c]=(counts[c]||0)+1;setExact(map);const total=Object.values(counts).reduce((a,b)=>a+b,0);let pool="";for(const c of "ABCDEFGHIJKLMNOPQRSTUVWXYZ"){const english=(counts[c]||0)/total,scrabble=SCRABBLE_COUNTS[c]/100,blended=(english+scrabble)/2;pool+=c.repeat(Math.max(1,Math.round(blended*1200)));}setLetterPool(pool);setDictionaryLoaded(true);}).catch(()=>setDictionaryLoaded(true));},[]);
  useEffect(()=>{const saved=localStorage.getItem("twiddler-config-v1");if(saved)try{const c=JSON.parse(saved);if(c.patterns)setPatterns(c.patterns);if(c.deckSize)setDeckSize(c.deckSize);if(Number.isInteger(c.boardSide))setBoardSide(Math.max(2,Math.min(6,c.boardSide)));if(Number.isInteger(c.startingHand))setStartingHand(c.startingHand);if(Number.isFinite(c.letterSpawnRate))setLetterSpawnRate(c.letterSpawnRate);if(c.wordColors)setWordColors(colors=>({...colors,...c.wordColors}));if(c.lineColor)setLineColor(c.lineColor);if(c.voidColor)setVoidColor(c.voidColor);if(c.themeId)setThemeId(c.themeId);if(c.surfaceColor)setSurfaceColor(c.surfaceColor);if(c.panelColor)setPanelColor(c.panelColor);if(c.tileColor)setTileColor(c.tileColor);if(c.accentColor)setAccentColor(c.accentColor);if(typeof c.warn==="boolean")setWarn(c.warn);if(typeof c.finder==="boolean")setFinder(c.finder);if(typeof c.chooseWord==="boolean")setChooseWord(c.chooseWord);}catch{}setConfigLoaded(true);},[]);
  useEffect(()=>{if(!configLoaded)return;localStorage.setItem("twiddler-config-v1",JSON.stringify({patterns,deckSize,boardSide,startingHand,letterSpawnRate,wordColors,lineColor,voidColor,themeId,surfaceColor,panelColor,tileColor,accentColor,warn,finder,chooseWord}));},[configLoaded,patterns,deckSize,boardSide,startingHand,letterSpawnRate,wordColors,lineColor,voidColor,themeId,surfaceColor,panelColor,tileColor,accentColor,warn,finder,chooseWord]);

  const randomLetter=useCallback(()=>letterPool[Math.floor(Math.random()*letterPool.length)]||"E",[letterPool]);
  const makeDeck=useCallback(()=>{let id=1;const counts=patterns.map(p=>Math.floor(deckSize*p.weight/100));while(counts.reduce((a,b)=>a+b,0)<deckSize){const i=counts.reduce((best,_,j)=>deckSize*patterns[j].weight/100-counts[j]>deckSize*patterns[best].weight/100-counts[best]?j:best,0);counts[i]++;}while(counts.reduce((a,b)=>a+b,0)>deckSize)counts[counts.indexOf(Math.max(...counts))]--;const cards:Tile[]=[];patterns.forEach((p,i)=>{for(let n=0;n<counts[i];n++){const letters=geometries[p.id].regions.map(()=>Math.random()*100<letterSpawnRate?randomLetter():"");if(!letters.some(Boolean))letters[Math.floor(Math.random()*letters.length)]=randomLetter();cards.push({id:id++,patternId:p.id,rotation:0,letters});}});return shuffle(cards);},[deckSize,patterns,geometries,randomLetter,letterSpawnRate]);

  const newGame=useCallback(()=>{const cards=makeDeck(),center=cards.shift()!;const openingHand=cards.splice(0,Math.min(startingHand,cards.length));const first=cards.shift();const dealt=first?[...openingHand,first]:openingHand;setBoard({"0,0":center});setDeck(cards);setHand(dealt);setHandSlots(Object.fromEntries(dealt.map((tile,i)=>[tile.id,i])));setHandSlotCount(dealt.length);setNewId(first?.id??null);setSelectedId(first?.id??dealt[0]?.id??null);setPreview(null);setScore(0);setDestroyedCount(0);setTurn(1);setHistory([]);setClosedNodes({});setPending(null);setGameOver(false);setConfigDirty(false);setTab("play");},[makeDeck,startingHand]);
  useEffect(()=>{if(configLoaded&&dictionaryLoaded&&!Object.keys(board).length&&patterns.length)newGame();},[configLoaded,dictionaryLoaded,newGame,board,patterns.length]);

  function getPattern(id:string){return patterns.find(p=>p.id===id)!;}
  function regionAtPort(tile:Placed,edge:number,port:number){const geo=geometries[tile.patternId];const localEdge=(edge-tile.rotation+60)%6;return geo.regions.find(r=>r.ports.some(([e,p])=>e===localEdge&&p===port))?.id;}

  const analyze=useCallback((candidate:Preview|null):Analysis=>{
    const temp={...board};if(candidate){const source=hand.find(t=>t.id===candidate.tileId);if(source)temp[candidate.cell]={...source,rotation:candidate.rotation};}
    const parent:Record<string,string>={};const nodes:string[]=[];
    for(const [cell,tile] of Object.entries(temp)){for(const r of geometries[tile.patternId].regions){const n=`${cell}|${r.id}`;parent[n]=n;nodes.push(n);}}
    const find=(x:string):string=>parent[x]===x?x:(parent[x]=find(parent[x]));const union=(a:string,b:string)=>{a=find(a);b=find(b);if(a!==b)parent[b]=a;};
    for(const [cell,tile] of Object.entries(temp)){const [q,r]=cell.split(",").map(Number);for(let e=0;e<6;e++){const nk=keyOf(q+DIRS[e][0],r+DIRS[e][1]),other=temp[nk];if(!other)continue;for(let p=0;p<2;p++){const a=regionAtPort(tile,e,p),b=regionAtPort(other,(e+3)%6,1-p);if(a!==undefined&&b!==undefined)union(`${cell}|${a}`,`${nk}|${b}`);}}}
    const groups=new Map<string,string[]>();for(const n of nodes){const root=find(n),arr=groups.get(root)||[];arr.push(n);groups.set(root,arr);}
    const canCache=new Map<string,boolean>();const comps:Component[]=[];
    for(const ns of groups.values()){let closed=true,dead=false;const letters:string[]=[];let touched=false;for(const node of ns){const [cell,riText]=node.split("|"),ri=+riText,tile=temp[cell],letter=tile.letters[ri];if(letter)letters.push(letter);if(candidate&&cell===candidate.cell)touched=true;const [q,r]=cell.split(",").map(Number),region=geometries[tile.patternId].regions[ri];for(const [le,port] of region.ports){const e=(le+tile.rotation)%6,nk=keyOf(q+DIRS[e][0],r+DIRS[e][1]);if(!temp[nk]){closed=false;if(!boardKeys.has(nk))dead=true;}else if(regionAtPort(temp[nk],(e+3)%6,1-port)===undefined)closed=false;}}
      const sig=signature(letters);let valid=true,possible:string[]=[];if(touched&&!dead){if(closed){if(letters.length===0)valid=true;else{possible=exact.get(sig)||[];valid=letters.length===1||possible.length>0;}}else if(letters.length===0)valid=true;else{if(canCache.has(sig))valid=canCache.get(sig)!;else{const need:Record<string,number>={};for(const c of letters)need[c]=(need[c]||0)+1;valid=words.some(w=>{if(w.length<letters.length)return false;const have:Record<string,number>={};for(const c of w)have[c]=(have[c]||0)+1;return Object.entries(need).every(([c,n])=>(have[c]||0)>=n);});canCache.set(sig,valid);}}}
      comps.push({nodes:ns,letters,closed,dead,touched,valid,words:possible});
    }
    const nodeStatus:Analysis["nodeStatus"]={};for(const c of comps){if(c.dead)for(const n of c.nodes)nodeStatus[n]="dead";else if(c.touched)for(const n of c.nodes)nodeStatus[n]=!c.valid?"invalid":c.closed?"closed":"affected";}
    const touched=comps.filter(c=>c.touched);return {components:comps,nodeStatus,valid:touched.every(c=>c.valid),closed:touched.filter(c=>c.closed)};
  },[board,hand,geometries,exact,words,boardKeys]);
  const restingAnalysis=useMemo(()=>analyze(null),[analyze]);
  const analysis=useMemo(()=>analyze(preview),[analyze,preview]);
  const isRegularWord=(c:Component)=>c.letters.length>1||c.words.length>0;
  const isVoidSingleton=(c:Component)=>c.letters.length===1&&c.words.length===0;
  const closingWords=analysis.closed.filter(isRegularWord);

  function colorForLength(length:number){if(length===0)return voidColor;if(length===1)return wordColors.one;if(length===2)return wordColors.two;if(length===3)return wordColors.three;if(length===4)return wordColors.four;if(length===5)return wordColors.five;if(length===6)return wordColors.six;return wordColors.sevenPlus;}
  function visualsFor(cell:string,tile:Tile){const status:Record<number,string>={},fills:Record<number,string>={},hidden:Record<number,boolean>={};geometries[tile.patternId].regions.forEach(r=>{const node=`${cell}|${r.id}`;hidden[r.id]=closedNodes[node]!==undefined||restingAnalysis.nodeStatus[node]==="dead";if(closedNodes[node]!==undefined){status[r.id]="complete";fills[r.id]=colorForLength(closedNodes[node]);return;}const analyzed=analysis.nodeStatus[node];if(analyzed==="dead"){status[r.id]="dead";fills[r.id]=voidColor;}else if(preview&&analyzed){status[r.id]=analyzed==="invalid"&&!warn&&!flash?"affected":analyzed;if(analyzed==="closed"){const component=analysis.components.find(c=>c.closed&&c.nodes.includes(node));if(component)fills[r.id]=isVoidSingleton(component)?voidColor:colorForLength(component.letters.length);}}});return {status,fills,hidden};}
  function setCandidate(cell:string,tileId=selectedId,rotation?:number){if(tileId===null||board[cell])return;const [q,r]=cell.split(",").map(Number);if(!DIRS.some(([dq,dr])=>board[keyOf(q+dq,r+dr)]))return;const resolvedRotation=rotation??hand.find(tile=>tile.id===tileId)?.rotation??0;setSelectedId(tileId);setPreview({cell,tileId,rotation:resolvedRotation});setFlash(false);}
  function returnPreviewToHand(){if(!preview)return;setHand(items=>items.map(tile=>tile.id===preview.tileId?{...tile,rotation:preview.rotation}:tile));setPreview(null);}
  function cancelPreview(){if(!preview)return;returnPreviewToHand();dragGhostRef.current?.remove();dragGhostRef.current=null;setDraggingId(null);setDragVisual(null);}
  function selectHandTile(tileId:number){if(preview&&preview.tileId!==tileId)returnPreviewToHand();setSelectedId(tileId);}
  function beginTileDrag(e:React.DragEvent<Element>,tileId:number,rotation:number){e.dataTransfer.effectAllowed="move";e.dataTransfer.setData("tile",String(tileId));e.dataTransfer.setData("rotation",String(rotation));dropAcceptedRef.current=false;dragGhostRef.current?.remove();const ghost=document.createElement("div");ghost.className="native-drag-ghost";document.body.appendChild(ghost);dragGhostRef.current=ghost;e.dataTransfer.setDragImage(ghost,0,0);const source=(e.currentTarget as Element).querySelector("svg")??e.currentTarget,size=source.getBoundingClientRect().width||95;setDragVisual({tileId,x:e.clientX,y:e.clientY,size});}
  function clearDragVisual(){dragGhostRef.current?.remove();dragGhostRef.current=null;setDraggingId(null);setDragVisual(null);}
  function finishTileDrag(fromPreview=false){clearDragVisual();if(!dropAcceptedRef.current&&fromPreview)cancelPreview();}
  useEffect(()=>{if(!dragVisual)return;const move=(e:DragEvent)=>{const boardRect=boardSvgRef.current?.getBoundingClientRect(),viewBox=boardSvgRef.current?.viewBox.baseVal,onBoard=Boolean(boardRect&&e.clientX>=boardRect.left&&e.clientX<=boardRect.right&&e.clientY>=boardRect.top&&e.clientY<=boardRect.bottom),boardSize=boardRect&&viewBox?.width&&viewBox?.height?Math.min(boardRect.width/viewBox.width,boardRect.height/viewBox.height)*100:72;setDragVisual(current=>current&&({...current,x:e.clientX,y:e.clientY,size:onBoard?boardSize:95}));};window.addEventListener("dragover",move);return()=>window.removeEventListener("dragover",move);},[Boolean(dragVisual)]);
  function finishGame(baseBoard=board,remainingHand=hand,remainingDeck=deck){const finalBoard={...baseBoard},empty=cells.filter(({q,r})=>!finalBoard[keyOf(q,r)]),available=shuffle([...remainingHand,...remainingDeck]);let nextId=Math.max(0,...Object.values(finalBoard).map(tile=>tile.id),...available.map(tile=>tile.id))+1;for(const cell of empty){const source=available.shift(),pattern=source?getPattern(source.patternId):patterns[Math.floor(Math.random()*patterns.length)];finalBoard[keyOf(cell.q,cell.r)]={id:source?.id??nextId++,patternId:pattern.id,rotation:source?.rotation??Math.floor(Math.random()*6),letters:geometries[pattern.id].regions.map(()=>"")};}setBoard(finalBoard);setClosedNodes(old=>{const next={...old};for(const [cell,tile] of Object.entries(finalBoard))for(const region of geometries[tile.patternId].regions){const node=`${cell}|${region.id}`;if(next[node]===undefined)next[node]=0;}return next;});setDestroyedCount(count=>count+available.length);setDeck([]);setHand([]);setHandSlots({});setPreview(null);setPending(null);setEntries([]);setSelectedId(null);setNewId(null);clearDragVisual();setGameOver(true);}
  function commit(wordsChosen:string[]=[]){if(!preview)return;const tile=hand.find(t=>t.id===preview.tileId);if(!tile)return;const slot=handSlots[tile.id],placed={...tile,rotation:preview.rotation},nextBoard={...board,[preview.cell]:placed},remaining=hand.filter(t=>t.id!==tile.id);setBoard(nextBoard);setHand(remaining);const wordClosures=analysis.closed.filter(isRegularWord),voidSingletons=analysis.closed.filter(isVoidSingleton),wordPoints=wordClosures.map(c=>c.nodes.length*Math.max(0,c.letters.length-1)),gained=wordPoints.reduce((a,b)=>a+b,0)-voidSingletons.length*5;setScore(s=>s+gained);if(analysis.closed.length)setClosedNodes(old=>{const next={...old};analysis.closed.forEach(c=>c.nodes.forEach(node=>next[node]=isVoidSingleton(c)?0:c.letters.length));return next;});setHistory(h=>[...h,{turn,words:wordsChosen,wordPoints,points:gained}]);setTurn(t=>t+1);setPreview(null);setPending(null);setEntries([]);if(Object.keys(nextBoard).length>=cells.length||(!deck.length&&!remaining.length))finishGame(nextBoard,remaining,deck);else drawNext(remaining,slot,tile.id);}
  function drawNext(remaining:Tile[],slot:number,removedId:number){if(deck.length){const [next,...rest]=deck;setDeck(rest);setHand([...remaining,next]);setHandSlots(slots=>{const updated={...slots};delete updated[removedId];updated[next.id]=slot;return updated;});setNewId(next.id);setSelectedId(next.id);}else{setHandSlots(slots=>{const updated={...slots};delete updated[removedId];return updated;});setNewId(null);setSelectedId(remaining[0]?.id??null);if(!remaining.length)setGameOver(true);}}
  function confirm(){if(!preview)return;if(!analysis.valid){setFlash(true);setTimeout(()=>setFlash(false),1300);return;}const wordClosures=analysis.closed.filter(isRegularWord);if(wordClosures.length){if(chooseWord){commit(wordClosures.map(c=>c.words[Math.floor(Math.random()*c.words.length)]));return;}const initial=wordClosures.map(c=>c.words.length===1?c.words[0]:"");if(initial.every(Boolean))commit(initial);else{setPending(wordClosures);setEntries(initial);}}else commit();}
  function submitWords(){if(!pending)return;const ok=pending.every((c,i)=>(exact.get(signature(c.letters))||[]).includes(entries[i].trim().toUpperCase()));if(!ok){setFlash(true);setTimeout(()=>setFlash(false),1300);return;}commit(entries.map(x=>x.trim().toUpperCase()));}
  function tradeTile(){if(selectedId===null||!deck.length)return;const slot=handSlots[selectedId],[next,...rest]=deck;setDeck(rest);setHand([...hand.filter(tile=>tile.id!==selectedId),next]);setHandSlots(slots=>{const updated={...slots};delete updated[selectedId];updated[next.id]=slot;return updated;});setDestroyedCount(count=>count+1);setNewId(next.id);setSelectedId(next.id);setPreview(null);setTurn(t=>t+1);}
  useEffect(()=>{const key=(e:KeyboardEvent)=>{if(!preview||pending)return;if(e.key.toLowerCase()==="r")setPreview(p=>p&&({...p,rotation:(p.rotation+1)%6}));if(e.key.toLowerCase()==="q")setPreview(p=>p&&({...p,rotation:(p.rotation+5)%6}));if(e.key==="Enter"){e.preventDefault();confirm();}if(e.key==="Escape"||e.key==="Delete"||e.key==="Backspace"){e.preventDefault();cancelPreview();}};window.addEventListener("keydown",key);return()=>window.removeEventListener("keydown",key);},[preview,pending,analysis]);

  const displayBoard=preview?{...board,[preview.cell]:{...hand.find(t=>t.id===preview.tileId)!,rotation:preview.rotation}}:board;
  const selected=hand.find(t=>t.id===selectedId);
  const totalWeight=patterns.reduce((n,p)=>n+p.weight,0);
  const coversEveryEdge=(pattern:Pattern)=>new Set(pattern.pairs.flat()).size===6;
  const configValid=configLoaded&&dictionaryLoaded&&patterns.length>0&&totalWeight===100&&patterns.every(coversEveryEdge);
  function addGeometry(){const number=patterns.length+1;setPatterns(ps=>[...ps,{id:`geometry-${Date.now()}`,label:`Geometry ${number}`,pairs:[[1,2],[3,4],[5,6]],weight:0}]);setConfigDirty(true);}
  function applyTheme(id:string){const theme=THEMES.find(item=>item.id===id);if(!theme)return;setThemeId(id);setSurfaceColor(theme.surface);setPanelColor(theme.panel);setTileColor(theme.tile);setLineColor(theme.line);setAccentColor(theme.accent);setVoidColor(theme.void);setWordColors(theme.words);}
  function confirmNewGame(){if(gameOver||window.confirm("Start a new game? Your current board and score will be lost."))newGame();}
  const foundWords=history.flatMap(item=>item.words.map((word,i)=>({word,points:item.wordPoints[i]??0})).filter(item=>item.word!=="PASS"));
  const handBySlot=Object.fromEntries(hand.map(tile=>[handSlots[tile.id],tile])) as Record<number,Tile>;
  const boardRadius=boardSide-1,viewWidth=boardRadius*159.4+140,viewHeight=boardRadius*138+140,targetTileSize=({2:120,3:100,4:82,5:68,6:58} as Record<number,number>)[boardSide]??82,boardDisplayWidth=viewWidth*targetTileSize/100;
  const palette=([{key:"one",label:"1"},{key:"two",label:"2"},{key:"three",label:"3"},{key:"four",label:"4"},{key:"five",label:"5"},{key:"six",label:"6"},{key:"sevenPlus",label:"7+"}] as {key:keyof WordColors;label:string}[]);
  function saveFinishedBoard(){if(!boardSvgRef.current)return;const svg=boardSvgRef.current.cloneNode(true) as SVGSVGElement,ns="http://www.w3.org/2000/svg";svg.setAttribute("xmlns",ns);svg.setAttribute("width","1200");svg.setAttribute("height","1200");svg.classList.remove("flash");const style=document.createElementNS(ns,"style");style.textContent=`.tile-paper{fill:${tileColor};stroke:#20251f;stroke-width:1.25}.wall{fill:none;stroke:${lineColor};stroke-width:4.5;stroke-linecap:round}.region-fill{fill:${voidColor}}.region-fill.complete{fill:${voidColor}}.empty-hex{fill:${voidColor};stroke:#20251f;stroke-width:1.25}.letter{font:900 12px Arial;text-anchor:middle;fill:#20251f;paint-order:stroke;stroke:${tileColor};stroke-width:2.5px}.cell{cursor:default}`;svg.prepend(style);const longest=[...foundWords].sort((a,b)=>b.word.length-a.word.length)[0]?.word;if(longest){const label=document.createElementNS(ns,"text");label.setAttribute("x","350");label.setAttribute("y","350");label.setAttribute("text-anchor","middle");label.setAttribute("dominant-baseline","middle");label.setAttribute("fill","#20251f");label.setAttribute("stroke",tileColor);label.setAttribute("stroke-width","5");label.setAttribute("paint-order","stroke");label.setAttribute("font-family","Georgia, serif");label.setAttribute("font-size",String(Math.max(24,Math.min(64,250/longest.length))));label.setAttribute("font-weight","700");label.textContent=longest;svg.append(label);}const blob=new Blob([new XMLSerializer().serializeToString(svg)],{type:"image/svg+xml"}),url=URL.createObjectURL(blob),link=document.createElement("a");link.href=url;link.download=`tiled-board-${new Date().toISOString().slice(0,10)}.svg`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}

  return <main style={{"--tile-line":lineColor,"--green":lineColor,"--void":voidColor,"--white":tileColor,"--paper":surfaceColor,"--panel":panelColor,"--orange":accentColor,background:surfaceColor} as CSSProperties}>
    {internal&&<header><div><p className="kicker">SOLO PLAYTEST / PROTOTYPE 01</p><h1>Twiddler</h1></div><nav><button className={tab==="play"?"active":""} disabled={configDirty} title={configDirty?"Generate a new game to apply your config changes":""} onClick={()=>setTab("play")}>Play</button><button className={tab==="lab"?"active":""} onClick={()=>setTab("lab")}>Game Config</button></nav><button className="new-game" disabled={!configValid} onClick={newGame}>New game</button></header>}
    {tab==="lab"?<section className={`lab ${internal?"":"public-config"}`}>
      {internal&&<div className="lab-intro"><p className="step">GAME CONFIG</p><h2>Shape the experiment.</h2><p>These settings take effect when you generate a new game. Each pattern must reach all six edge midpoints.</p></div>}
      <div className="lab-card">{!internal&&<div className="public-config-heading"><div><p className="step">GAME CONFIG</p><h2>Settings</h2></div><button onClick={()=>setTab("play")}>Back to game</button></div>}<div className="lab-row"><label>Total tile supply<input type="number" min="5" max="100" value={deckSize} onChange={e=>{setDeckSize(Math.max(5,+e.target.value));setConfigDirty(true);}}/></label><label>Board edge<input type="number" min="2" max="6" value={boardSide} onChange={e=>{setBoardSide(Math.max(2,Math.min(6,+e.target.value)));setConfigDirty(true);}}/></label><label>Starting hand<input type="number" min="0" max="12" value={startingHand} onChange={e=>{setStartingHand(Math.max(0,Math.min(12,+e.target.value)));setConfigDirty(true);}}/></label><span className={totalWeight===100?"weight-ok":"weight-bad"}>{totalWeight}% total</span></div>
      <div className="theme-setting"><label>Visual theme<select value={themeId} onChange={e=>applyTheme(e.target.value)}>{THEMES.map(theme=><option key={theme.id} value={theme.id}>{theme.name}</option>)}</select></label></div><div className="play-options"><label><input type="checkbox" checked={warn} onChange={e=>setWarn(e.target.checked)}/> Warn before confirming</label><label><input type="checkbox" checked={finder} onChange={e=>setFinder(e.target.checked)}/> Show word finder</label><label><input type="checkbox" checked={chooseWord} onChange={e=>setChooseWord(e.target.checked)}/> Choose words for me</label></div><div className="letter-settings"><label>Letter spawn rate<input type="range" min="0" max="100" step="5" value={letterSpawnRate} onChange={e=>{setLetterSpawnRate(+e.target.value);setConfigDirty(true);}}/><strong>{letterSpawnRate}%</strong></label><div className="color-settings"><span>Colors</span><label>Tile<input type="color" value={tileColor} onChange={e=>setTileColor(e.target.value)}/></label><label>Panel<input type="color" value={panelColor} onChange={e=>setPanelColor(e.target.value)}/></label><label>Line<input type="color" value={lineColor} onChange={e=>setLineColor(e.target.value)}/></label><label>Accent<input type="color" value={accentColor} onChange={e=>setAccentColor(e.target.value)}/></label><label>Void<input type="color" value={voidColor} onChange={e=>setVoidColor(e.target.value)}/></label>{palette.map(item=><label key={item.key}>{item.label}<input type="color" value={wordColors[item.key]} onChange={e=>setWordColors(colors=>({...colors,[item.key]:e.target.value}))}/></label>)}</div></div>
      <div className="geometry-heading"><div><strong>Tile geometries</strong><span>Every edge must appear at least once.</span></div><button onClick={addGeometry}>+ Add geometry</button></div>
      {patterns.map((p,i)=><div className={`pattern-row ${coversEveryEdge(p)?"":"pattern-invalid"}`} key={p.id}><div className="mini"><TileFace tile={{id:0,patternId:p.id,letters:geometries[p.id].regions.map(()=>"·"),rotation:0}} pattern={p} geometry={geometries[p.id]}/></div><label>Name<input value={p.label} onChange={e=>{setPatterns(ps=>ps.map((x,j)=>j===i?{...x,label:e.target.value}:x));setConfigDirty(true);}}/></label><label>Edge pairs<input defaultValue={p.pairs.map(x=>x.join("-")).join(", ")} onBlur={e=>{const pairs=parsePairs(e.target.value);if(pairs){setPatterns(ps=>ps.map((x,j)=>j===i?{...x,pairs}:x));setConfigDirty(true);}else e.target.value=p.pairs.map(x=>x.join("-")).join(", ");}}/></label><label>Weight<input type="number" min="0" max="100" value={p.weight} onChange={e=>{setPatterns(ps=>ps.map((x,j)=>j===i?{...x,weight:+e.target.value}:x));setConfigDirty(true);}}/></label><button className="delete-geometry" disabled={patterns.length===1} title="Delete geometry" onClick={()=>{setPatterns(ps=>ps.filter((_,j)=>j!==i));setConfigDirty(true);}}>×</button></div>)}
      {!patterns.every(coversEveryEdge)&&<p className="config-error">Each geometry must use all six edge numbers before a game can be generated.</p>}
      <button className="primary" disabled={!configValid} onClick={newGame}>Generate & play</button></div>
    </section>:<div className={`game-layout ${internal?"internal-layout":"public-layout"}`}>
      <aside className="left-rail"><section className="score-card"><span>SCORE</span><strong>{score}</strong><small>Turn {turn}<i>{deck.length} tiles in deck</i></small></section><section className="side-hand"><div className="tray-title"><p className="rail-label">YOUR HAND</p></div><div className="hand-cards">{Array.from({length:handSlotCount},(_,slot)=>{const tile=handBySlot[slot];if(!tile||tile.id===preview?.tileId)return <span className="hand-slot-empty" key={`slot-${slot}`}/>;const p=getPattern(tile.patternId);return <button key={tile.id} draggable onDragStart={e=>{selectHandTile(tile.id);beginTileDrag(e,tile.id,tile.rotation);setDraggingId(tile.id);}} onDragEnd={()=>finishTileDrag()} onClick={()=>selectHandTile(tile.id)} className={`hand-tile ${selectedId===tile.id?"selected":""} ${draggingId===tile.id?"dragging":""}`}><TileFace tile={tile} pattern={p} geometry={geometries[p.id]}/>{newId===tile.id&&<b>NEW</b>}</button>})}</div><div className="hand-actions"><button className="pass" disabled={gameOver||selectedId===null||!deck.length} onClick={tradeTile}>Trade selected tile</button><button className={`end-game ${gameOver?"restart":""}`} onClick={()=>gameOver?newGame():finishGame()}>{gameOver?"New game":"End game"}</button></div></section></aside>
      <section className="board-stage">{internal?<div className="stage-top"><div><p className="step">TURN {String(turn).padStart(2,"0")}</p><h2>{gameOver?"Game complete":preview?"Check the sections":"Place one tile"}</h2></div><div className="config-chip"><span>{deckSize}-tile deck · {letterSpawnRate}% letters · {patterns.length} patterns</span>{gameOver&&<button className="save-board" onClick={saveFinishedBoard}>Save tiled board SVG</button>}</div></div>:<div className="board-tools">{gameOver&&<button className="save-board" onClick={saveFinishedBoard}>Save tiled board SVG</button>}<button aria-label="How to play" title="How to play" onClick={()=>setShowInstructions(true)}>?</button><button aria-label="Game config" title="Game config" onClick={()=>setTab("lab")}>⚙</button><button aria-label="Start a new game" title="Start a new game" onClick={confirmNewGame}>↻</button></div>}
      <svg ref={boardSvgRef} className={`board ${flash?"flash":""}`} style={{width:`min(100%, ${boardDisplayWidth}px)`}} viewBox={`${350-viewWidth/2} ${350-viewHeight/2} ${viewWidth} ${viewHeight}`} onDragOver={e=>e.preventDefault()}>
        {cells.map(({q,r})=>{const cell=keyOf(q,r),x=350+79.7*(q+r/2),y=350+69*r,tile=displayBoard[cell],visual=tile?visualsFor(cell,tile):null;const adjacent=DIRS.some(([dq,dr])=>board[keyOf(q+dq,r+dr)]),isPreview=preview?.cell===cell;return <g key={cell} transform={`translate(${x-50} ${y-50})`} className={`cell ${tile?"filled":adjacent?"available":""}`} {...({draggable:isPreview} as Record<string,boolean>)} onDragStart={e=>{if(isPreview&&preview)beginTileDrag(e,preview.tileId,preview.rotation);}} onDragEnd={()=>finishTileDrag(true)} onClick={()=>!tile&&setCandidate(cell)} onDragOver={e=>{if(!tile&&adjacent){e.preventDefault();e.dataTransfer.dropEffect="move";}}} onDrop={e=>{e.preventDefault();dropAcceptedRef.current=true;clearDragVisual();const rotation=Number(e.dataTransfer.getData("rotation"));setCandidate(cell,+e.dataTransfer.getData("tile"),Number.isFinite(rotation)?rotation:undefined);}}>{tile?<TileFace tile={tile} pattern={getPattern(tile.patternId)} geometry={geometries[tile.patternId]} status={visual!.status} fills={visual!.fills} hidden={isPreview?{}:visual!.hidden} preview={isPreview}/>:<svg width="100" height="100" viewBox="0 0 100 100"><polygon points={HEX.map(p=>p.join(",")).join(" ")} className="empty-hex"/></svg>}</g>;})}
      </svg>
      {preview&&<div className="confirm-bar"><div><span>{closingWords.length?`${closingWords.length} word section${closingWords.length>1?"s":""} will close`:analysis.closed.length?`${analysis.closed.length} empty shape${analysis.closed.length>1?"s":""} will close`:"No section closes"}</span><small>{analysis.valid?"Every affected section remains playable.":warn?"This placement creates an impossible section.":"Confirm to test this placement."}</small></div><button onClick={()=>setPreview(p=>p&&({...p,rotation:(p.rotation+5)%6}))}>Q ↺</button><button onClick={()=>setPreview(p=>p&&({...p,rotation:(p.rotation+1)%6}))}>R ↻</button><button className="quiet" onClick={cancelPreview}>Cancel</button><button className="primary" disabled={warn&&!analysis.valid} onClick={confirm}>Confirm</button></div>}
      </section>
      {internal?<aside className="right-rail"><section className="theme-panel"><p className="rail-label">VISUAL THEME</p><select value={themeId} onChange={e=>applyTheme(e.target.value)}>{THEMES.map(theme=><option key={theme.id} value={theme.id}>{theme.name}</option>)}</select><p>Inspired palettes; adjust any color below.</p></section><section className="play-palette"><p className="rail-label">COLORS</p><div><label><input type="color" value={tileColor} onChange={e=>setTileColor(e.target.value)}/>Tile</label><label><input type="color" value={surfaceColor} onChange={e=>setSurfaceColor(e.target.value)}/>Ground</label><label><input type="color" value={panelColor} onChange={e=>setPanelColor(e.target.value)}/>Panel</label><label><input type="color" value={lineColor} onChange={e=>setLineColor(e.target.value)}/>Line</label><label><input type="color" value={accentColor} onChange={e=>setAccentColor(e.target.value)}/>Accent</label><label><input type="color" value={voidColor} onChange={e=>setVoidColor(e.target.value)}/>Void</label>{palette.map(item=><label key={item.key}><input type="color" value={wordColors[item.key]} onChange={e=>setWordColors(colors=>({...colors,[item.key]:e.target.value}))}/>{item.label}</label>)}</div></section></aside>:<aside className="found-panel"><div><p className="rail-label">FOUND WORDS</p><span>{foundWords.length} found</span></div><div className="found-list">{foundWords.length?foundWords.map((item,i)=><b key={`${item.word}-${i}`} style={{borderColor:colorForLength(item.word.length)}}>{item.word} {item.points}</b>):<p>No words yet.</p>}</div></aside>}
      {internal&&<section className="word-tray"><div><p className="rail-label">FOUND WORDS</p><span>{foundWords.length} found</span></div><div className="bottom-words">{foundWords.length?foundWords.map((item,i)=><b key={`${item.word}-${i}`} style={{borderColor:colorForLength(item.word.length)}}>{item.word} {item.points}</b>):<p>No words yet.</p>}</div></section>}
    </div>}
    {showInstructions&&<div className="modal-backdrop"><div className="instructions-modal"><button className="modal-close" aria-label="Close instructions" onClick={()=>setShowInstructions(false)}>×</button><p className="step">HOW TO PLAY</p><h2>Place tiles on the board to form words.</h2><ol><li>Choose a tile from your hand and place it next to a tile already on the board.</li><li>Rotate the tile with Q and R. When you are happy with it, confirm the placement.</li><li>The lines divide the board into spaces. When you close a space, its letters (in any order) must spell a word.</li><li>Longer words and larger spaces score more points. A and I are allowed, but they score zero points. Other single letters can be closed alone, but you lose 5 points.</li><li>If you do not want to play a tile, trade it for the next tile in the deck. The old tile is removed from the game.</li><li>The game ends when the board is full, you run out of tiles, or you press End game.</li></ol><button className="primary" onClick={()=>setShowInstructions(false)}>Got it</button></div></div>}
    {pending&&<div className="modal-backdrop"><div className={`word-modal ${flash?"shake":""}`}><p className="step">CLOSED SECTION{pending.filter(c=>c.words.length!==1).length>1?"S":""}</p><h2>Name the word{pending.filter(c=>c.words.length!==1).length>1?"s":""}.</h2>{pending.map((c,i)=>c.words.length===1?null:<div className="word-entry" key={i}><div className="letters">{c.letters.map((l,j)=><span key={j}>{l}</span>)}</div>{finder&&<p className="hints">Possible: {c.words.slice(0,8).join(" · ")}</p>}<input autoFocus={entries.findIndex((_,j)=>pending[j].words.length!==1)===i} value={entries[i]} onChange={e=>setEntries(x=>x.map((v,j)=>j===i?e.target.value.toUpperCase():v))} onKeyDown={e=>{if(e.key==="Enter")submitWords();}} placeholder="Type a valid anagram"/></div>)}<div className="modal-actions"><button className="quiet" onClick={()=>setPending(null)}>Back to placement</button><button className="primary" onClick={submitWords}>Submit & score</button></div></div></div>}
    {dragVisual&&(()=>{const tile=hand.find(item=>item.id===dragVisual.tileId),pattern=tile&&getPattern(tile.patternId);return tile&&pattern?<div className="tile-drag-follow" style={{left:dragVisual.x,top:dragVisual.y,width:dragVisual.size,height:dragVisual.size}}><TileFace tile={preview?.tileId===tile.id?{...tile,rotation:preview.rotation}:tile} pattern={pattern} geometry={geometries[pattern.id]} preview/></div>:null;})()}
  </main>;
}
