import { useCallback, useEffect, useMemo, useRef, useState, type CSSProperties } from "react";
import { analyzePattern, cellsForSide, curvePath, DIRS, HEX, keyOf, PATTERNS, Pattern, PatternGeometry, shuffle, signature, Tile } from "./game";
import generatedTemplates from "./puzzle-calibration.json";
import "./globals.css";

type Placed = Tile;
type Preview = { cell:string; tileId:number; rotation:number };
type Component = { nodes:string[]; letters:string[]; closed:boolean; dead:boolean; touched:boolean; valid:boolean; words:string[] };
type Analysis = { components:Component[]; nodeStatus:Record<string,"affected"|"closed"|"invalid"|"dead">; valid:boolean; closed:Component[] };
type HistoryItem = { turn:number; words:string[]; wordPoints:number[]; points:number };
type WordColors = { one:string; two:string; three:string; four:string; five:string; six:string; sevenPlus:string };
type Theme = { id:string; name:string; surface:string; panel:string; tile:string; line:string; accent:string; void:string; words:WordColors };
type Difficulty="easy"|"medium"|"hard";
type PuzzleSpec={word:string;tier:Difficulty;template:number;duplicateClues:number;totalLetters:number};
type PuzzleTemplate={patterns:string[];solutionRotations:number[];targetSlots:[number,number][];safeRegions:number[][];centerClues?:[number,number,number][];centerConstraint?:boolean;metrics:{centerPattern:string;centerPatternCopies:number;targetUsesCenter:boolean;targetTileCount:number;targetComponentSize:number}};

const FALLBACK_FREQ="EEEEEEEEEEEEAAAAAAAAAIIIIIIIIIOOOOOOOONNNNNNRRRRRRTTTTTTLLLLSSSSUUUUDDDDGGGBBCCMMPPFFHHVVWWYYKJXQZ";
const SCRABBLE_COUNTS:Record<string,number>={A:9,B:2,C:2,D:4,E:12,F:2,G:3,H:2,I:9,J:1,K:1,L:4,M:2,N:6,O:8,P:2,Q:1,R:6,S:4,T:6,U:4,V:2,W:2,X:1,Y:2,Z:1};
const SHORT_WORDS=["A","I","AA","AB","AD","AE","AG","AH","AI","AL","AM","AN","AR","AS","AT","AW","AX","AY","BA","BE","BI","BO","BY","DA","DE","DO","ED","EF","EH","EL","EM","EN","ER","ES","ET","EW","EX","FA","FE","GI","GO","GU","HA","HE","HI","HM","HO","ID","IF","IN","IO","IS","IT","JA","JO","KA","KI","KO","KY","LA","LI","LO","MA","ME","MI","MM","MO","MU","MY","NA","NE","NG","NI","NO","NU","OD","OE","OF","OH","OI","OM","ON","OP","OR","OS","OU","OW","OX","OY","PA","PE","PI","PO","QI","RE","SH","SI","SO","TA","TE","TI","TO","UH","UM","UN","UP","US","UT","WE","WO","XI","XU","YA","YE","YO","ZA"];
const THEMES:Theme[]=[
  {id:"talavera",name:"Talavera Courtyard",surface:"#f1eadc",panel:"#e7ddcb",tile:"#fff8e8",line:"#b65b3d",accent:"#2f6390",void:"#d8d0c2",words:{one:"#8aa9a1",two:"#2a7f7a",three:"#d8a51d",four:"#c9543f",five:"#608449",six:"#d48642",sevenPlus:"#376b85"}},
  {id:"iznik",name:"İznik Evening",surface:"#eeeae3",panel:"#e0e4e7",tile:"#fffaf0",line:"#304f82",accent:"#b6484f",void:"#d7d9dc",words:{one:"#8a9eb5",two:"#2d8c91",three:"#365c9a",four:"#705083",five:"#b6484f",six:"#587d9d",sevenPlus:"#80627f"}},
  {id:"mediterranean",name:"Mediterranean Grove",surface:"#eee9df",panel:"#e3ddcf",tile:"#faf6eb",line:"#626b50",accent:"#a54d3d",void:"#d5d0c5",words:{one:"#a3a58e",two:"#77804e",three:"#c2763f",four:"#a54d3d",five:"#60777a",six:"#a98251",sevenPlus:"#875b50"}},
  {id:"castilian",name:"Castilian Sky",surface:"#edf0ee",panel:"#e0e6e6",tile:"#fcfdfb",line:"#5e568c",accent:"#c99b18",void:"#dce1e1",words:{one:"#8baaa5",two:"#d9b633",three:"#27928e",four:"#6d9a4b",five:"#d46a52",six:"#6486a7",sevenPlus:"#82639a"}},
  {id:"zellige",name:"Zellige Garden",surface:"#eee9dc",panel:"#e4dccb",tile:"#fff9e9",line:"#376b5a",accent:"#b47a25",void:"#d7d0c0",words:{one:"#83a49b",two:"#238b88",three:"#386a9a",four:"#d0a23a",five:"#a44f42",six:"#55805d",sevenPlus:"#665b8c"}},
];
const PUZZLE_TEMPLATES=generatedTemplates as PuzzleTemplate[];
const PUZZLES:PuzzleSpec[]=[
  {word:"STAR",tier:"easy",template:0,duplicateClues:6,totalLetters:14},{word:"MOON",tier:"easy",template:1,duplicateClues:6,totalLetters:15},{word:"PEAR",tier:"easy",template:2,duplicateClues:5,totalLetters:15},{word:"FROG",tier:"easy",template:3,duplicateClues:5,totalLetters:16},{word:"MAPLE",tier:"easy",template:4,duplicateClues:6,totalLetters:16},{word:"BEACH",tier:"easy",template:5,duplicateClues:5,totalLetters:17},{word:"TIGER",tier:"easy",template:6,duplicateClues:5,totalLetters:17},{word:"COOKIE",tier:"easy",template:7,duplicateClues:6,totalLetters:18},{word:"PLANET",tier:"easy",template:8,duplicateClues:5,totalLetters:18},{word:"RAINBOW",tier:"easy",template:9,duplicateClues:5,totalLetters:19},
  {word:"WAVE",tier:"medium",template:10,duplicateClues:3,totalLetters:19},{word:"MINT",tier:"medium",template:11,duplicateClues:3,totalLetters:20},{word:"PLUM",tier:"medium",template:12,duplicateClues:2,totalLetters:21},{word:"CORAL",tier:"medium",template:13,duplicateClues:3,totalLetters:21},{word:"ROBIN",tier:"medium",template:14,duplicateClues:2,totalLetters:22},{word:"HONEY",tier:"medium",template:15,duplicateClues:3,totalLetters:22},{word:"CASTLE",tier:"medium",template:16,duplicateClues:3,totalLetters:23},{word:"TURTLE",tier:"medium",template:17,duplicateClues:3,totalLetters:23},{word:"COMPASS",tier:"medium",template:18,duplicateClues:3,totalLetters:24},{word:"OCTOPUS",tier:"medium",template:19,duplicateClues:2,totalLetters:24},
  {word:"KITE",tier:"hard",template:20,duplicateClues:1,totalLetters:23},{word:"LIME",tier:"hard",template:21,duplicateClues:1,totalLetters:24},{word:"MOSS",tier:"hard",template:22,duplicateClues:1,totalLetters:24},{word:"BRICK",tier:"hard",template:23,duplicateClues:1,totalLetters:25},{word:"GRAPE",tier:"hard",template:24,duplicateClues:1,totalLetters:26},{word:"FLAME",tier:"hard",template:25,duplicateClues:0,totalLetters:26},{word:"JUNGLE",tier:"hard",template:26,duplicateClues:1,totalLetters:27},{word:"RABBIT",tier:"hard",template:27,duplicateClues:1,totalLetters:27},{word:"LANTERN",tier:"hard",template:28,duplicateClues:1,totalLetters:28},{word:"DOLPHIN",tier:"hard",template:29,duplicateClues:0,totalLetters:28},
  {word:"LEMON",tier:"easy",template:30,duplicateClues:5,totalLetters:17},{word:"PRETZEL",tier:"hard",template:31,duplicateClues:1,totalLetters:28},{word:"TRACTOR",tier:"hard",template:32,duplicateClues:1,totalLetters:28},{word:"MERMAID",tier:"hard",template:33,duplicateClues:1,totalLetters:28},
  {word:"SHARK",tier:"medium",template:34,duplicateClues:4,totalLetters:21},{word:"OTTER",tier:"medium",template:35,duplicateClues:5,totalLetters:22},{word:"KOALA",tier:"medium",template:36,duplicateClues:5,totalLetters:22},{word:"GARDEN",tier:"medium",template:37,duplicateClues:4,totalLetters:23},{word:"PEBBLE",tier:"medium",template:38,duplicateClues:5,totalLetters:23},{word:"CICADA",tier:"medium",template:39,duplicateClues:5,totalLetters:24},{word:"PENGUIN",tier:"medium",template:40,duplicateClues:4,totalLetters:24},{word:"GIRAFFE",tier:"medium",template:41,duplicateClues:4,totalLetters:24},{word:"HAMSTER",tier:"medium",template:42,duplicateClues:3,totalLetters:25},{word:"CHICKEN",tier:"medium",template:43,duplicateClues:4,totalLetters:25},
  {word:"WOLF",tier:"medium",template:44,duplicateClues:4,totalLetters:26},{word:"JADE",tier:"medium",template:45,duplicateClues:4,totalLetters:25},{word:"ECHO",tier:"medium",template:46,duplicateClues:3,totalLetters:25},{word:"SQUID",tier:"medium",template:47,duplicateClues:4,totalLetters:27},{word:"MANGO",tier:"medium",template:48,duplicateClues:4,totalLetters:26},{word:"COBRA",tier:"medium",template:49,duplicateClues:3,totalLetters:26},{word:"RAVEN",tier:"medium",template:50,duplicateClues:4,totalLetters:27},{word:"BADGER",tier:"medium",template:51,duplicateClues:3,totalLetters:27},{word:"WALNUT",tier:"medium",template:52,duplicateClues:3,totalLetters:27},{word:"RACCOON",tier:"medium",template:53,duplicateClues:4,totalLetters:27},
  {word:"LYNX",tier:"medium",template:54,duplicateClues:3,totalLetters:25},{word:"PEAK",tier:"medium",template:55,duplicateClues:4,totalLetters:25},{word:"SWAN",tier:"medium",template:56,duplicateClues:4,totalLetters:26},{word:"HORSE",tier:"medium",template:57,duplicateClues:4,totalLetters:26},{word:"PEACH",tier:"medium",template:58,duplicateClues:4,totalLetters:26},{word:"STORM",tier:"medium",template:59,duplicateClues:3,totalLetters:27},{word:"PANDA",tier:"medium",template:60,duplicateClues:4,totalLetters:27},{word:"KITTEN",tier:"medium",template:61,duplicateClues:4,totalLetters:27},{word:"ROCKET",tier:"medium",template:62,duplicateClues:3,totalLetters:28},{word:"ORCHARD",tier:"medium",template:63,duplicateClues:3,totalLetters:28},
  {word:"FERN",tier:"medium",template:64,duplicateClues:3,totalLetters:26},{word:"DOVE",tier:"medium",template:65,duplicateClues:4,totalLetters:26},{word:"RUBY",tier:"medium",template:66,duplicateClues:3,totalLetters:26},{word:"GECKO",tier:"medium",template:67,duplicateClues:4,totalLetters:27},{word:"PLANT",tier:"medium",template:68,duplicateClues:3,totalLetters:27},{word:"BREAD",tier:"medium",template:69,duplicateClues:4,totalLetters:27},{word:"WHALE",tier:"medium",template:70,duplicateClues:3,totalLetters:27},{word:"MAGNET",tier:"medium",template:71,duplicateClues:3,totalLetters:28},{word:"COYOTE",tier:"medium",template:72,duplicateClues:4,totalLetters:28},{word:"MONARCH",tier:"medium",template:73,duplicateClues:3,totalLetters:28},
  {word:"COZY",tier:"medium",template:74,duplicateClues:3,totalLetters:26},{word:"BOOK",tier:"medium",template:75,duplicateClues:4,totalLetters:26},{word:"CAKE",tier:"medium",template:76,duplicateClues:3,totalLetters:26},{word:"GLOW",tier:"medium",template:77,duplicateClues:3,totalLetters:26},{word:"PIZZA",tier:"medium",template:78,duplicateClues:4,totalLetters:27},{word:"DONUT",tier:"medium",template:79,duplicateClues:3,totalLetters:27},{word:"DISCO",tier:"medium",template:80,duplicateClues:4,totalLetters:27},{word:"MAGIC",tier:"medium",template:81,duplicateClues:3,totalLetters:27},{word:"DREAM",tier:"medium",template:82,duplicateClues:3,totalLetters:27},{word:"BUBBLE",tier:"medium",template:83,duplicateClues:4,totalLetters:28},{word:"PICKLE",tier:"medium",template:84,duplicateClues:3,totalLetters:28},{word:"WAFFLE",tier:"medium",template:85,duplicateClues:4,totalLetters:28},{word:"SUNSET",tier:"medium",template:86,duplicateClues:3,totalLetters:28},{word:"CIRCUS",tier:"medium",template:87,duplicateClues:3,totalLetters:28},{word:"COFFEE",tier:"medium",template:88,duplicateClues:4,totalLetters:28},{word:"CUPCAKE",tier:"medium",template:89,duplicateClues:3,totalLetters:28},{word:"BALLOON",tier:"medium",template:90,duplicateClues:4,totalLetters:28},{word:"SPARKLE",tier:"medium",template:91,duplicateClues:3,totalLetters:28},{word:"PANCAKE",tier:"medium",template:92,duplicateClues:3,totalLetters:28},{word:"FESTIVE",tier:"medium",template:93,duplicateClues:3,totalLetters:28},
];
const FEATURED_PUZZLES=["CAKE","GECKO","DISCO","SQUID","WAFFLE","DOVE","MERMAID","PICKLE","CIRCUS","TRACTOR"];
const DECOY_POOL="EEEEEEEEAAAAAAAIIIIIIIOOOOOOONNNNNNRRRRRRTTTTTTLLLLSSSSUUUUDDDDGGGBBCCMMPPFFHHVVWWYYKJXQZ";
const parsePairs=(value:string)=>{const out:[number,number][]=[];for(const part of value.split(",")){const m=part.trim().match(/^([1-6])\s*[-–:]\s*([1-6])$/);if(!m||m[1]===m[2])return null;out.push([+m[1],+m[2]]);}return out;};

function TileFace({tile,pattern,geometry,status={},fills={},hidden={},preview=false}:{tile:Tile;pattern:Pattern;geometry:PatternGeometry;status?:Record<number,string>;fills?:Record<number,string>;hidden?:Record<number,boolean>;preview?:boolean}){
  return <svg width="100" height="100" viewBox="0 0 100 100" className={preview?"tile-svg preview":"tile-svg"} aria-hidden="true">
    <polygon points={HEX.map(p=>p.join(",")).join(" ")} className="tile-paper" />
    <g transform={`rotate(${tile.rotation*60} 50 50)`}>
      {geometry.regions.map((region)=><path key={region.id} d={region.mask} className={`region-fill ${status[region.id]||""}`} style={fills[region.id]?{fill:fills[region.id]}:undefined} />)}
      {pattern.pairs.map((pair,i)=><path key={i} d={curvePath(pair)} className="wall" />)}
      {geometry.regions.map((region)=>tile.letters[region.id]&&!hidden[region.id]&&<text key={`l${region.id}`} x={region.cx} y={region.cy+4.2} transform={preview?undefined:`rotate(${-tile.rotation*60} ${region.cx} ${region.cy})`} className="letter">{tile.letters[region.id]}</text>)}
    </g>
    <polygon points={HEX.map(p=>p.join(",")).join(" ")} className="tile-outline" />
  </svg>;
}

function RotateIcon({direction}:{direction:"left"|"right"}){return direction==="left"?<svg className="control-icon" viewBox="0 0 24 24" aria-hidden="true"><path d="M20 15a8 8 0 0 0-8-10H7"/><path d="m10 2-3 3 3 3"/></svg>:<svg className="control-icon" viewBox="0 0 24 24" aria-hidden="true"><path d="M4 15a8 8 0 0 1 8-10h5"/><path d="m14 2 3 3-3 3"/></svg>}
function HomeIcon(){return <svg className="control-icon home-icon" viewBox="0 0 24 24" aria-hidden="true"><path d="m3 11 9-8 9 8"/><path d="M5 10v10h14V10M9 20v-6h6v6"/></svg>}

export default function App(){
  const internal=false;
  const [tab,setTab]=useState<"play"|"lab">("play");
  const [patterns,setPatterns]=useState<Pattern[]>(PATTERNS);
  const [deckSize,setDeckSize]=useState(7);
  const [boardSide,setBoardSide]=useState(2);
  const [startingHand,setStartingHand]=useState(7);
  const [letterSpawnRate,setLetterSpawnRate]=useState(60);
  const [wordColors,setWordColors]=useState<WordColors>(THEMES[4].words);
  const [lineColor,setLineColor]=useState(THEMES[4].line);
  const [voidColor,setVoidColor]=useState(THEMES[4].void);
  const [themeId,setThemeId]=useState("zellige");
  const [surfaceColor,setSurfaceColor]=useState(THEMES[4].surface);
  const [panelColor,setPanelColor]=useState(THEMES[4].panel);
  const [tileColor,setTileColor]=useState(THEMES[4].tile);
  const [accentColor,setAccentColor]=useState(THEMES[4].accent);
  const [configDirty,setConfigDirty]=useState(false);
  const [configLoaded,setConfigLoaded]=useState(true);
  const [dictionaryLoaded,setDictionaryLoaded]=useState(false);
  const geometries=useMemo(()=>Object.fromEntries(patterns.map(p=>[p.id,analyzePattern(p)])),[patterns]);
  const cells=useMemo(()=>cellsForSide(boardSide),[boardSide]);
  const boardKeys=useMemo(()=>new Set(cells.map(({q,r})=>keyOf(q,r))),[cells]);
  const [words,setWords]=useState<string[]>([]);
  const [exact,setExact]=useState<Map<string,string[]>>(new Map());
  const [letterPool,setLetterPool]=useState(FALLBACK_FREQ);
  const [board,setBoard]=useState<Record<string,Placed>>({});
  const [deck,setDeck]=useState<Tile[]>([]);
  const [hand,setHand]=useState<Tile[]>([]);
  const [handSlots,setHandSlots]=useState<Record<number,number>>({});
  const [handSlotCount,setHandSlotCount]=useState(0);
  const [newId,setNewId]=useState<number|null>(null);
  const [selectedId,setSelectedId]=useState<number|null>(null);
  const [selectedCell,setSelectedCell]=useState<string|null>(null);
  const [draggingId,setDraggingId]=useState<number|null>(null);
  const [dragVisual,setDragVisual]=useState<{tileId:number;x:number;y:number;size:number}|null>(null);
  const [preview,setPreview]=useState<Preview|null>(null);
  const [score,setScore]=useState(0);
  const [,setDestroyedCount]=useState(0);
  const [turn,setTurn]=useState(1);
  const [history,setHistory]=useState<HistoryItem[]>([]);
  const [closedNodes,setClosedNodes]=useState<Record<string,number>>({});
  const [warn,setWarn]=useState(false);
  const [finder,setFinder]=useState(true);
  const [chooseWord,setChooseWord]=useState(false);
  const [showInstructions,setShowInstructions]=useState(false);
  const [showPuzzleSelector,setShowPuzzleSelector]=useState(false);
  const [flash,setFlash]=useState(false);
  const [pending,setPending]=useState<Component[]|null>(null);
  const [entries,setEntries]=useState<string[]>([]);
  const [gameOver,setGameOver]=useState(false);
  const [won,setWon]=useState(false);
  const [hintMode,setHintMode]=useState(false);
  const [activePuzzle,setActivePuzzle]=useState(76);
  const [completedWords,setCompletedWords]=useState<Set<string>>(()=>new Set());
  const boardSvgRef=useRef<SVGSVGElement|null>(null);
  const dragGhostRef=useRef<HTMLElement|null>(null);
  const dropAcceptedRef=useRef(false);
  const suppressBoardClickRef=useRef(false);

  useEffect(()=>{fetch("../words.txt").then(r=>r.text()).then(text=>{const longWords=text.split(/\s+/).filter(w=>w.length>=3),list=[...SHORT_WORDS,...longWords];setWords(list);const map=new Map<string,string[]>(),counts:Record<string,number>={};for(const word of list){const sig=signature(word);const arr=map.get(sig)||[];if(arr.length<30)arr.push(word);map.set(sig,arr);}for(const word of longWords)for(const c of word)counts[c]=(counts[c]||0)+1;setExact(map);const total=Object.values(counts).reduce((a,b)=>a+b,0);let pool="";for(const c of "ABCDEFGHIJKLMNOPQRSTUVWXYZ"){const english=(counts[c]||0)/total,scrabble=SCRABBLE_COUNTS[c]/100,blended=(english+scrabble)/2;pool+=c.repeat(Math.max(1,Math.round(blended*1200)));}setLetterPool(pool);setDictionaryLoaded(true);}).catch(()=>setDictionaryLoaded(true));},[]);

  const randomLetter=useCallback(()=>letterPool[Math.floor(Math.random()*letterPool.length)]||"E",[letterPool]);
  const makeDeck=useCallback(()=>{let id=1;const counts=patterns.map(p=>Math.floor(deckSize*p.weight/100));while(counts.reduce((a,b)=>a+b,0)<deckSize){const i=counts.reduce((best,_,j)=>deckSize*patterns[j].weight/100-counts[j]>deckSize*patterns[best].weight/100-counts[best]?j:best,0);counts[i]++;}while(counts.reduce((a,b)=>a+b,0)>deckSize)counts[counts.indexOf(Math.max(...counts))]--;const cards:Tile[]=[];patterns.forEach((p,i)=>{for(let n=0;n<counts[i];n++){const letters=geometries[p.id].regions.map(()=>Math.random()*100<letterSpawnRate?randomLetter():"");if(!letters.some(Boolean))letters[Math.floor(Math.random()*letters.length)]=randomLetter();cards.push({id:id++,patternId:p.id,rotation:0,letters});}});return shuffle(cards);},[deckSize,patterns,geometries,randomLetter,letterSpawnRate]);

  const puzzle=PUZZLES[activePuzzle],puzzleTemplate=PUZZLE_TEMPLATES[puzzle.template];
  function createPuzzleTiles(index:number){const spec=PUZZLES[index],template=PUZZLE_TEMPLATES[spec.template],tiles=template.patterns.map((patternId,i)=>({id:i+1,patternId,rotation:Math.floor(Math.random()*6),letters:geometries[patternId].regions.map(()=>"")}));template.targetSlots.forEach(([tile,region],i)=>tiles[tile].letters[region]=spec.word[i]);template.centerClues?.forEach(([tile,region,letterIndex])=>tiles[tile].letters[region]=spec.word[letterIndex]);let seed=[...spec.word].reduce((n,c)=>((n*33+c.charCodeAt(0))>>>0),5381),random=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;};const slots=template.safeRegions.flatMap((regions,tile)=>regions.map(region=>({tile,region}))).filter(slot=>!tiles[slot.tile].letters[slot.region]&&(!template.centerConstraint||slot.region!==0||geometries[tiles[slot.tile].patternId].regions[0].ports.length<4));for(let i=slots.length-1;i>0;i--){const j=Math.floor(random()*(i+1));[slots[i],slots[j]]=[slots[j],slots[i]];}const rarity="ZQXJKVBPYGFWMUCLDRHSONITEA",unique=[...new Set(spec.word)].sort((a,b)=>rarity.indexOf(a)-rarity.indexOf(b)),extras=[...Array(spec.duplicateClues)].map((_,i)=>unique[i%unique.length]);while(extras.length<spec.totalLetters-spec.word.length-(template.centerClues?.length??0))extras.push(DECOY_POOL[Math.floor(random()*DECOY_POOL.length)]);slots.slice(0,extras.length).forEach((slot,i)=>tiles[slot.tile].letters[slot.region]=extras[i]);tiles.forEach((tile,i)=>{if(!tile.letters.some(Boolean)&&template.safeRegions[i][0]!==undefined)tile.letters[template.safeRegions[i][0]]=DECOY_POOL[Math.floor(random()*DECOY_POOL.length)];});return tiles;}
  function startPuzzle(index:number){const dealt=createPuzzleTiles(index);setActivePuzzle(index);setBoard({});setDeck([]);setHand(dealt);setHandSlots(Object.fromEntries(dealt.map((tile,i)=>[tile.id,i])));setHandSlotCount(dealt.length);setNewId(null);setSelectedId(dealt[0]?.id??null);setSelectedCell(null);setPreview(null);setScore(0);setDestroyedCount(0);setTurn(1);setHistory([]);setClosedNodes({});setPending(null);setGameOver(false);setWon(false);setHintMode(false);setConfigDirty(false);setTab("play");}
  const newGame=useCallback(()=>startPuzzle(activePuzzle),[activePuzzle,geometries]);
  useEffect(()=>{if(configLoaded&&dictionaryLoaded&&!Object.keys(board).length&&!hand.length&&patterns.length)newGame();},[configLoaded,dictionaryLoaded,newGame,board,hand.length,patterns.length]);

  function getPattern(id:string){return patterns.find(p=>p.id===id)!;}
  function hintHidden(tile:Tile){const targets=new Set(puzzleTemplate.targetSlots.filter(([tileIndex])=>tileIndex===tile.id-1).map(([,region])=>region));return hintMode?Object.fromEntries(geometries[tile.patternId].regions.map(region=>[region.id,!targets.has(region.id)])):{};}
  function regionAtPort(tile:Placed,edge:number,port:number){const geo=geometries[tile.patternId];const localEdge=(edge-tile.rotation+60)%6;return geo.regions.find(r=>r.ports.some(([e,p])=>e===localEdge&&p===port))?.id;}

  const analyze=useCallback((candidate:Preview|null):Analysis=>{
    const temp={...board};if(candidate){const source=hand.find(t=>t.id===candidate.tileId);if(source)temp[candidate.cell]={...source,rotation:candidate.rotation};}
    const parent:Record<string,string>={};const nodes:string[]=[];
    for(const [cell,tile] of Object.entries(temp)){for(const r of geometries[tile.patternId].regions){const n=`${cell}|${r.id}`;parent[n]=n;nodes.push(n);}}
    const find=(x:string):string=>parent[x]===x?x:(parent[x]=find(parent[x]));const union=(a:string,b:string)=>{a=find(a);b=find(b);if(a!==b)parent[b]=a;};
    for(const [cell,tile] of Object.entries(temp)){const [q,r]=cell.split(",").map(Number);for(let e=0;e<6;e++){const nk=keyOf(q+DIRS[e][0],r+DIRS[e][1]),other=temp[nk];if(!other)continue;for(let p=0;p<2;p++){const a=regionAtPort(tile,e,p),b=regionAtPort(other,(e+3)%6,1-p);if(a!==undefined&&b!==undefined)union(`${cell}|${a}`,`${nk}|${b}`);}}}
    const groups=new Map<string,string[]>();for(const n of nodes){const root=find(n),arr=groups.get(root)||[];arr.push(n);groups.set(root,arr);}
    const canCache=new Map<string,boolean>();const comps:Component[]=[];
    for(const ns of groups.values()){let closed=true,dead=false;const letters:string[]=[];let touched=false;for(const node of ns){const [cell,riText]=node.split("|"),ri=+riText,tile=temp[cell],letter=tile.letters[ri];if(letter)letters.push(letter);if(candidate&&cell===candidate.cell)touched=true;const [q,r]=cell.split(",").map(Number),region=geometries[tile.patternId].regions[ri];for(const [le,port] of region.ports){const e=(le+tile.rotation)%6,nk=keyOf(q+DIRS[e][0],r+DIRS[e][1]);if(!temp[nk]){closed=false;if(!boardKeys.has(nk))dead=true;}else if(regionAtPort(temp[nk],(e+3)%6,1-port)===undefined)closed=false;}}
      const sig=signature(letters);let valid=true,possible:string[]=[];if(touched&&!dead){if(closed){if(letters.length===0)valid=true;else{possible=exact.get(sig)||[];valid=letters.length===1||possible.length>0;}}else if(letters.length===0)valid=true;else{if(canCache.has(sig))valid=canCache.get(sig)!;else{const need:Record<string,number>={};for(const c of letters)need[c]=(need[c]||0)+1;valid=words.some(w=>{if(w.length<letters.length)return false;const have:Record<string,number>={};for(const c of w)have[c]=(have[c]||0)+1;return Object.entries(need).every(([c,n])=>(have[c]||0)>=n);});canCache.set(sig,valid);}}}
      comps.push({nodes:ns,letters,closed,dead,touched,valid,words:possible});
    }
    const nodeStatus:Analysis["nodeStatus"]={};for(const c of comps){if(c.dead)for(const n of c.nodes)nodeStatus[n]="dead";else if(c.touched)for(const n of c.nodes)nodeStatus[n]=!c.valid?"invalid":c.closed?"closed":"affected";}
    const touched=comps.filter(c=>c.touched);return {components:comps,nodeStatus,valid:touched.every(c=>c.valid),closed:touched.filter(c=>c.closed)};
  },[board,hand,geometries,exact,words,boardKeys]);
  const restingAnalysis=useMemo(()=>analyze(null),[analyze]);
  const analysis=useMemo(()=>analyze(preview),[analyze,preview]);
  const isRegularWord=(c:Component)=>c.letters.length>1||c.words.length>0;
  const isVoidSingleton=(c:Component)=>c.letters.length===1&&c.words.length===0;
  const closingWords=analysis.closed.filter(isRegularWord);

  function colorForLength(length:number){if(length===0)return voidColor;if(length===1)return wordColors.one;if(length===2)return wordColors.two;if(length===3)return wordColors.three;if(length===4)return wordColors.four;if(length===5)return wordColors.five;if(length===6)return wordColors.six;return wordColors.sevenPlus;}
  function visualsFor(cell:string,tile:Tile){const status:Record<number,string>={},fills:Record<number,string>={},hidden:Record<number,boolean>={};geometries[tile.patternId].regions.forEach(r=>{const node=`${cell}|${r.id}`,component=restingAnalysis.components.find(c=>c.nodes.includes(node));hidden[r.id]=false;if(!component)return;if(component.dead){status[r.id]="dead";fills[r.id]=voidColor;}else if(component.closed){const possible=exact.get(signature(component.letters))||[],voided=component.letters.length===0||(component.letters.length===1&&!possible.length);status[r.id]=voided?"dead":possible.length?"closed":"invalid";fills[r.id]=voided?voidColor:possible.length?colorForLength(component.letters.length):"#dba39d";}else status[r.id]="affected";});return {status,fills,hidden};}
  function setCandidate(cell:string,tileId=selectedId,rotation?:number){if(board[cell]||gameOver)return;if(selectedCell){const tile=board[selectedCell];if(!tile)return;setBoard(current=>{const next={...current};delete next[selectedCell];next[cell]=tile;return next;});setSelectedCell(cell);setFlash(false);return;}if(tileId===null)return;const tile=hand.find(item=>item.id===tileId);if(!tile)return;const placed={...tile,rotation:rotation??tile.rotation};setBoard(current=>({...current,[cell]:placed}));setHand(items=>items.filter(item=>item.id!==tileId));setSelectedId(null);setSelectedCell(cell);setFlash(false);}
  function returnBoardTileToHand(cell:string){const tile=board[cell];if(!tile||gameOver)return;setBoard(current=>{const next={...current};delete next[cell];return next;});setHand(items=>items.some(item=>item.id===tile.id)?items:[...items,tile]);setSelectedCell(null);setSelectedId(tile.id);setFlash(false);}
  function moveBoardTile(source:string,destination:string){if(source===destination||board[destination]||gameOver)return;const tile=board[source];if(!tile)return;setBoard(current=>{const next={...current};delete next[source];next[destination]=tile;return next;});setSelectedCell(destination);setSelectedId(null);setFlash(false);}
  function beginBoardPointerDrag(e:React.PointerEvent<SVGGElement>,cell:string,tile:Tile){if(gameOver||e.button!==0)return;const startX=e.clientX,startY=e.clientY,sourceSize=(e.currentTarget.querySelector("svg")??e.currentTarget).getBoundingClientRect().width||95;let moved=false;const move=(event:PointerEvent)=>{if(!moved&&Math.hypot(event.clientX-startX,event.clientY-startY)<4)return;moved=true;setDragVisual({tileId:tile.id,x:event.clientX,y:event.clientY,size:sourceSize});};const up=(event:PointerEvent)=>{window.removeEventListener("pointermove",move);window.removeEventListener("pointerup",up);clearDragVisual();if(!moved)return;suppressBoardClickRef.current=true;setTimeout(()=>{suppressBoardClickRef.current=false;},0);const target=document.elementFromPoint(event.clientX,event.clientY);if(target?.closest("[data-hand-drop]"))returnBoardTileToHand(cell);else{const destination=target?.closest("[data-board-cell]")?.getAttribute("data-board-cell");if(destination&&!board[destination])moveBoardTile(cell,destination);}};window.addEventListener("pointermove",move);window.addEventListener("pointerup",up,{once:true});}
  function returnPreviewToHand(){if(!preview)return;setHand(items=>items.map(tile=>tile.id===preview.tileId?{...tile,rotation:preview.rotation}:tile));setPreview(null);}
  function cancelPreview(){if(!preview)return;returnPreviewToHand();dragGhostRef.current?.remove();dragGhostRef.current=null;setDraggingId(null);setDragVisual(null);}
  function selectHandTile(tileId:number){if(preview&&preview.tileId!==tileId)returnPreviewToHand();setSelectedCell(null);setSelectedId(tileId);}
  function beginTileDrag(e:React.DragEvent<Element>,tileId:number,rotation:number){e.dataTransfer.effectAllowed="move";e.dataTransfer.setData("tile",String(tileId));e.dataTransfer.setData("rotation",String(rotation));dropAcceptedRef.current=false;dragGhostRef.current?.remove();const ghost=document.createElement("div");ghost.className="native-drag-ghost";document.body.appendChild(ghost);dragGhostRef.current=ghost;e.dataTransfer.setDragImage(ghost,0,0);const source=(e.currentTarget as Element).querySelector("svg")??e.currentTarget,size=source.getBoundingClientRect().width||95;setDragVisual({tileId,x:e.clientX,y:e.clientY,size});}
  function clearDragVisual(){dragGhostRef.current?.remove();dragGhostRef.current=null;setDraggingId(null);setDragVisual(null);}
  function finishTileDrag(fromPreview=false){clearDragVisual();if(!dropAcceptedRef.current&&fromPreview)cancelPreview();}
  useEffect(()=>{if(!dragVisual)return;const move=(e:DragEvent)=>{const boardRect=boardSvgRef.current?.getBoundingClientRect(),viewBox=boardSvgRef.current?.viewBox.baseVal,onBoard=Boolean(boardRect&&e.clientX>=boardRect.left&&e.clientX<=boardRect.right&&e.clientY>=boardRect.top&&e.clientY<=boardRect.bottom),boardSize=boardRect&&viewBox?.width&&viewBox?.height?Math.min(boardRect.width/viewBox.width,boardRect.height/viewBox.height)*100:72;setDragVisual(current=>current&&({...current,x:e.clientX,y:e.clientY,size:onBoard?boardSize:95}));};window.addEventListener("dragover",move);return()=>window.removeEventListener("dragover",move);},[Boolean(dragVisual)]);
  function finishGame(baseBoard=board,remainingHand=hand,remainingDeck=deck){const finalBoard={...baseBoard},empty=cells.filter(({q,r})=>!finalBoard[keyOf(q,r)]),available=shuffle([...remainingHand,...remainingDeck]);let nextId=Math.max(0,...Object.values(finalBoard).map(tile=>tile.id),...available.map(tile=>tile.id))+1;for(const cell of empty){const source=available.shift(),pattern=source?getPattern(source.patternId):patterns[Math.floor(Math.random()*patterns.length)];finalBoard[keyOf(cell.q,cell.r)]={id:source?.id??nextId++,patternId:pattern.id,rotation:source?.rotation??Math.floor(Math.random()*6),letters:geometries[pattern.id].regions.map(()=>"")};}setBoard(finalBoard);setClosedNodes(old=>{const next={...old};for(const [cell,tile] of Object.entries(finalBoard))for(const region of geometries[tile.patternId].regions){const node=`${cell}|${region.id}`;if(next[node]===undefined)next[node]=0;}return next;});setDestroyedCount(count=>count+available.length);setDeck([]);setHand([]);setHandSlots({});setPreview(null);setPending(null);setEntries([]);setSelectedId(null);setNewId(null);clearDragVisual();setGameOver(true);}
  function commit(wordsChosen:string[]=[]){if(!preview)return;const tile=hand.find(t=>t.id===preview.tileId);if(!tile)return;const placed={...tile,rotation:preview.rotation},nextBoard={...board,[preview.cell]:placed},remaining=hand.filter(t=>t.id!==tile.id),solved=wordsChosen.includes(puzzle.word);setBoard(nextBoard);setHand(remaining);const wordClosures=analysis.closed.filter(isRegularWord),voidSingletons=analysis.closed.filter(isVoidSingleton),wordPoints=wordClosures.map(c=>c.nodes.length*Math.max(0,c.letters.length-1)),gained=wordPoints.reduce((a,b)=>a+b,0)-voidSingletons.length*5;setScore(s=>s+gained);if(analysis.closed.length)setClosedNodes(old=>{const next={...old};analysis.closed.forEach(c=>c.nodes.forEach(node=>next[node]=isVoidSingleton(c)?0:c.letters.length));return next;});setHistory(h=>[...h,{turn,words:wordsChosen,wordPoints,points:gained}]);setTurn(t=>t+1);setPreview(null);setPending(null);setEntries([]);setHandSlots(slots=>{const updated={...slots};delete updated[tile.id];return updated;});setSelectedId(remaining[0]?.id??null);if(solved){setWon(true);setGameOver(true);}else if(!remaining.length)setGameOver(true);}
  function drawNext(remaining:Tile[],slot:number,removedId:number){if(deck.length){const [next,...rest]=deck;setDeck(rest);setHand([...remaining,next]);setHandSlots(slots=>{const updated={...slots};delete updated[removedId];updated[next.id]=slot;return updated;});setNewId(next.id);setSelectedId(next.id);}else{setHandSlots(slots=>{const updated={...slots};delete updated[removedId];return updated;});setNewId(null);setSelectedId(remaining[0]?.id??null);if(!remaining.length)setGameOver(true);}}
  function confirm(){if(!preview)return;if(!analysis.valid){setFlash(true);setTimeout(()=>setFlash(false),1300);return;}const wordClosures=analysis.closed.filter(isRegularWord);if(wordClosures.length){if(chooseWord){commit(wordClosures.map(c=>c.words[Math.floor(Math.random()*c.words.length)]));return;}const initial=wordClosures.map(c=>c.words.length===1?c.words[0]:"");if(initial.every(Boolean))commit(initial);else{setPending(wordClosures);setEntries(initial);}}else commit();}
  function submitWords(){if(!pending)return;const ok=pending.every((c,i)=>(exact.get(signature(c.letters))||[]).includes(entries[i].trim().toUpperCase()));if(!ok){setFlash(true);setTimeout(()=>setFlash(false),1300);return;}commit(entries.map(x=>x.trim().toUpperCase()));}
  function tradeTile(){if(selectedId===null||!deck.length)return;const slot=handSlots[selectedId],[next,...rest]=deck;setDeck(rest);setHand([...hand.filter(tile=>tile.id!==selectedId),next]);setHandSlots(slots=>{const updated={...slots};delete updated[selectedId];updated[next.id]=slot;return updated;});setDestroyedCount(count=>count+1);setNewId(next.id);setSelectedId(next.id);setPreview(null);setTurn(t=>t+1);}
  function rotateSelected(delta:number){if(gameOver)return;if(selectedCell)setBoard(current=>({...current,[selectedCell]:{...current[selectedCell],rotation:(current[selectedCell].rotation+delta+6)%6}}));else if(selectedId!==null)setHand(items=>items.map(tile=>tile.id===selectedId?{...tile,rotation:(tile.rotation+delta+6)%6}:tile));}
  function confirmPuzzle(){if(Object.keys(board).length!==cells.length)return;const target=restingAnalysis.components.find(component=>component.closed&&signature(component.letters)===signature(puzzle.word)),invalidOther=restingAnalysis.components.some(component=>component.closed&&component!==target&&component.letters.length>1&&!(exact.get(signature(component.letters))||[]).length);if(!target||invalidOther){setFlash(true);setTimeout(()=>setFlash(false),1300);return;}const points=target.nodes.length*Math.max(0,puzzle.word.length-1);setWon(true);setGameOver(true);setCompletedWords(done=>new Set(done).add(puzzle.word));setScore(points);setHistory([{turn:1,words:[puzzle.word],wordPoints:[points],points}]);setClosedNodes(Object.fromEntries(target.nodes.map(node=>[node,puzzle.word.length])));setSelectedCell(null);setSelectedId(null);}
  function nextPuzzle(){const current=FEATURED_PUZZLES.indexOf(puzzle.word),ordered=FEATURED_PUZZLES.map((_,offset)=>FEATURED_PUZZLES[(current+1+offset)%FEATURED_PUZZLES.length]),next=ordered.find(word=>!completedWords.has(word))??ordered[0],index=PUZZLES.findIndex(item=>item.word===next);if(index>=0)startPuzzle(index);}
  useEffect(()=>{const key=(e:KeyboardEvent)=>{if(pending)return;if(e.key.toLowerCase()==="r")rotateSelected(1);if(e.key.toLowerCase()==="q")rotateSelected(-1);if(e.key==="Enter"&&Object.keys(board).length===cells.length){e.preventDefault();confirmPuzzle();}if((e.key==="Escape"||e.key==="Delete"||e.key==="Backspace")&&selectedCell){e.preventDefault();returnBoardTileToHand(selectedCell);}};window.addEventListener("keydown",key);return()=>window.removeEventListener("keydown",key);},[pending,selectedCell,selectedId,board,restingAnalysis,cells.length,gameOver]);

  const displayBoard=preview?{...board,[preview.cell]:{...hand.find(t=>t.id===preview.tileId)!,rotation:preview.rotation}}:board;
  const selected=hand.find(t=>t.id===selectedId);
  const totalWeight=patterns.reduce((n,p)=>n+p.weight,0);
  const coversEveryEdge=(pattern:Pattern)=>new Set(pattern.pairs.flat()).size===6;
  const configValid=configLoaded&&dictionaryLoaded&&patterns.length>0&&totalWeight===100&&patterns.every(coversEveryEdge);
  function addGeometry(){const number=patterns.length+1;setPatterns(ps=>[...ps,{id:`geometry-${Date.now()}`,label:`Geometry ${number}`,pairs:[[1,2],[3,4],[5,6]],weight:0}]);setConfigDirty(true);}
  function applyTheme(id:string){const theme=THEMES.find(item=>item.id===id);if(!theme)return;setThemeId(id);setSurfaceColor(theme.surface);setPanelColor(theme.panel);setTileColor(theme.tile);setLineColor(theme.line);setAccentColor(theme.accent);setVoidColor(theme.void);setWordColors(theme.words);}
  function confirmNewGame(){if(gameOver||window.confirm("Reset the current game?"))newGame();}
  const foundWords=history.flatMap(item=>item.words.map((word,i)=>({word,points:item.wordPoints[i]??0})).filter(item=>item.word!=="PASS"));
  const handBySlot=Object.fromEntries(hand.map(tile=>[handSlots[tile.id],tile])) as Record<number,Tile>;
  const boardRadius=boardSide-1,viewWidth=boardRadius*159.4+140,viewHeight=boardRadius*138+140,targetTileSize=({2:120,3:100,4:82,5:68,6:58} as Record<number,number>)[boardSide]??82,boardDisplayWidth=viewWidth*targetTileSize/100;
  const palette=([{key:"one",label:"1"},{key:"two",label:"2"},{key:"three",label:"3"},{key:"four",label:"4"},{key:"five",label:"5"},{key:"six",label:"6"},{key:"sevenPlus",label:"7+"}] as {key:keyof WordColors;label:string}[]);
  function saveFinishedBoard(){if(!boardSvgRef.current)return;const svg=boardSvgRef.current.cloneNode(true) as SVGSVGElement,ns="http://www.w3.org/2000/svg";svg.setAttribute("xmlns",ns);svg.setAttribute("width","1200");svg.setAttribute("height","1200");svg.classList.remove("flash");const style=document.createElementNS(ns,"style");style.textContent=`.tile-paper{fill:${tileColor};stroke:#20251f;stroke-width:1.25}.wall{fill:none;stroke:${lineColor};stroke-width:4.5;stroke-linecap:round}.region-fill{fill:${voidColor}}.region-fill.complete{fill:${voidColor}}.empty-hex{fill:${voidColor};stroke:#20251f;stroke-width:1.25}.letter{font:900 12px Arial;text-anchor:middle;fill:#20251f;paint-order:stroke;stroke:${tileColor};stroke-width:2.5px}.cell{cursor:default}`;svg.prepend(style);const longest=[...foundWords].sort((a,b)=>b.word.length-a.word.length)[0]?.word;if(longest){const label=document.createElementNS(ns,"text");label.setAttribute("x","350");label.setAttribute("y","350");label.setAttribute("text-anchor","middle");label.setAttribute("dominant-baseline","middle");label.setAttribute("fill","#20251f");label.setAttribute("stroke",tileColor);label.setAttribute("stroke-width","5");label.setAttribute("paint-order","stroke");label.setAttribute("font-family","Georgia, serif");label.setAttribute("font-size",String(Math.max(24,Math.min(64,250/longest.length))));label.setAttribute("font-weight","700");label.textContent=longest;svg.append(label);}const blob=new Blob([new XMLSerializer().serializeToString(svg)],{type:"image/svg+xml"}),url=URL.createObjectURL(blob),link=document.createElement("a");link.href=url;link.download=`tiled-board-${new Date().toISOString().slice(0,10)}.svg`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}

  return <main style={{"--tile-line":lineColor,"--green":lineColor,"--void":voidColor,"--white":tileColor,"--paper":surfaceColor,"--panel":panelColor,"--orange":accentColor,background:surfaceColor} as CSSProperties}>
    {internal&&<header><div><p className="kicker">SOLO PLAYTEST / PROTOTYPE 01</p><h1>Twiddler</h1></div><nav><button className={tab==="play"?"active":""} disabled={configDirty} title={configDirty?"Generate a new game to apply your config changes":""} onClick={()=>setTab("play")}>Play</button><button className={tab==="lab"?"active":""} onClick={()=>setTab("lab")}>Game Config</button></nav><button className="new-game" disabled={!configValid} onClick={newGame}>New game</button></header>}
    {tab==="lab"?<section className="puzzle-picker"><div className="puzzle-picker-heading"><div><p className="step">PUZZLE LIBRARY</p><h2>Choose a word.</h2><p>Each hand has at least one verified arrangement that closes its title word.</p></div><button onClick={()=>setTab("play")}>Back to puzzle</button></div>{(["easy","medium","hard"] as Difficulty[]).map(tier=><section key={tier}><div><h3>{tier}</h3><span>{tier==="easy"?"More repeated clues · fewer decoys":tier==="medium"?"Some repeated clues · moderate decoys":"Less repetition · dense decoys"}</span></div><div className="puzzle-grid">{PUZZLES.map((item,index)=>item.tier===tier?<button key={item.word} className={activePuzzle===index?"active":""} onClick={()=>startPuzzle(index)}><b>{item.word}</b><small>{item.word.length} letters</small></button>:null)}</div></section>)}</section>:<div className={`game-layout ${internal?"internal-layout":"public-layout"}`}>
      <aside className="left-rail" data-hand-drop onDragOver={e=>{if(e.dataTransfer.types.includes("board-cell"))e.preventDefault();}} onDrop={e=>{const source=e.dataTransfer.getData("board-cell");if(source){e.preventDefault();returnBoardTileToHand(source);clearDragVisual();}}}><section className="score-card"><span>PUZZLE</span><strong>{puzzle.word}{won&&<i className="puzzle-complete-mark" aria-label="Complete">✓</i>}</strong></section><section className="side-hand"><div className="tray-title"><p className="rail-label">YOUR TILES</p></div><div className="hand-cards">{Array.from({length:handSlotCount},(_,slot)=>{const tile=handBySlot[slot];if(!tile)return <span className="hand-slot-empty" key={`slot-${slot}`}/>;const p=getPattern(tile.patternId);return <button key={tile.id} draggable={!gameOver} onDragStart={e=>{selectHandTile(tile.id);beginTileDrag(e,tile.id,tile.rotation);setDraggingId(tile.id);}} onDragEnd={()=>finishTileDrag()} onClick={()=>!gameOver&&selectHandTile(tile.id)} className={`hand-tile ${selectedId===tile.id?"selected":""} ${draggingId===tile.id?"dragging":""}`}><TileFace tile={tile} pattern={p} geometry={geometries[p.id]} hidden={hintHidden(tile)}/></button>})}</div><div className="hand-actions"><button className={`end-game ${gameOver?"restart":""}`} onClick={newGame}>{gameOver?"Play again":"Restart puzzle"}</button></div></section></aside>
      <section className="board-stage">{internal?<div className="stage-top"><div><p className="step">TURN {String(turn).padStart(2,"0")}</p><h2>{gameOver?"Game complete":preview?"Check the sections":"Place one tile"}</h2></div></div>:<div className="board-tools"><strong className="mobile-puzzle-title">Twiddler</strong><button className="mobile-only mobile-puzzle-button" onClick={()=>setShowPuzzleSelector(true)}>Puzzles</button>{gameOver&&<button className="save-board" onClick={saveFinishedBoard}>Save tiled board SVG</button>}<button aria-label="How to play" title="How to play" onClick={()=>setShowInstructions(true)}>?</button><button aria-label="Restart puzzle" title="Restart puzzle" onClick={confirmNewGame}>↻</button></div>}
      <svg ref={boardSvgRef} className={`board ${flash?"flash":""}`} style={{width:`min(100%, ${boardDisplayWidth}px)`}} viewBox={`${350-viewWidth/2} ${350-viewHeight/2} ${viewWidth} ${viewHeight}`} onDragOver={e=>e.preventDefault()}>
        {cells.map(({q,r})=>{
          const cell=keyOf(q,r),x=350+79.7*(q+r/2),y=350+69*r,tile=displayBoard[cell],visual=tile?visualsFor(cell,tile):null;
          const selectCell=()=>{if(suppressBoardClickRef.current)return;if(tile){setSelectedCell(cell);setSelectedId(null);}else setCandidate(cell);};
          return <g key={cell} data-board-cell={cell} transform={`translate(${x-50} ${y-50})`} className={`cell ${tile?"filled":"available"} ${selectedCell===cell?"puzzle-selected":""}`} onPointerDown={e=>{if(tile)beginBoardPointerDrag(e,cell,tile);}} onClick={selectCell} onDragOver={e=>{if(!tile){e.preventDefault();e.dataTransfer.dropEffect="move";}}} onDrop={e=>{e.preventDefault();clearDragVisual();const rotation=Number(e.dataTransfer.getData("rotation"));setCandidate(cell,+e.dataTransfer.getData("tile"),Number.isFinite(rotation)?rotation:undefined);}}>{tile?<TileFace tile={tile} pattern={getPattern(tile.patternId)} geometry={geometries[tile.patternId]} status={visual!.status} fills={visual!.fills} hidden={hintHidden(tile)}/>:<svg width="100" height="100" viewBox="0 0 100 100"><polygon points={HEX.map(p=>p.join(",")).join(" ")} className="empty-hex"/></svg>}</g>;
        })}
        {cells.map(({q,r})=>{const cell=keyOf(q,r);if(displayBoard[cell])return null;const x=350+79.7*(q+r/2),y=350+69*r;return <g key={`outline-${cell}`} transform={`translate(${x-50} ${y-50})`} pointerEvents="none"><svg width="100" height="100" viewBox="0 0 100 100"><polygon points={HEX.map(p=>p.join(",")).join(" ")} className="empty-hex-overlay"/></svg></g>;})}
        {cells.map(({q,r})=>{const cell=keyOf(q,r);if(!displayBoard[cell])return null;const x=350+79.7*(q+r/2),y=350+69*r;return <g key={`solid-outline-${cell}`} transform={`translate(${x-50} ${y-50})`} pointerEvents="none"><svg width="100" height="100" viewBox="0 0 100 100"><polygon points={HEX.map(p=>p.join(",")).join(" ")} className="board-solid-outline"/></svg></g>;})}
        {selectedCell&&displayBoard[selectedCell]&&(()=>{const [q,r]=selectedCell.split(",").map(Number),x=350+79.7*(q+r/2),y=350+69*r;return <g transform={`translate(${x-50} ${y-50})`} pointerEvents="none"><svg width="100" height="100" viewBox="0 0 100 100"><polygon points={HEX.map(p=>p.join(",")).join(" ")} className="board-selection-outline"/></svg></g>;})()}
      </svg>
      {!gameOver&&<div className="mobile-tile-controls"><button aria-label="Rotate selected tile left" disabled={!selectedCell&&selectedId===null} onClick={()=>rotateSelected(-1)}><RotateIcon direction="left"/></button><button aria-label="Return selected tile to hand" disabled={!selectedCell} onClick={()=>selectedCell&&returnBoardTileToHand(selectedCell)}><HomeIcon/></button><button aria-label="Rotate selected tile right" disabled={!selectedCell&&selectedId===null} onClick={()=>rotateSelected(1)}><RotateIcon direction="right"/></button></div>}
      {!internal&&<strong className="mobile-target-word">{puzzle.word}</strong>}
      {!internal&&<div className={`mobile-confirm-action ${won?"won":""} ${flash?"error":""}`}>{won?<button className="primary" onClick={nextPuzzle}>Next Puzzle</button>:<button className="primary" aria-label="Confirm puzzle" disabled={Object.keys(board).length!==cells.length} onClick={confirmPuzzle}>✓</button>}</div>}
      {!gameOver?<div className={`confirm-bar puzzle-confirm ${flash?"shake":""}`}><div><span>{flash?`That arrangement does not validly close ${puzzle.word}.`:Object.keys(board).length===cells.length?"All seven tiles are placed.":`${Object.keys(board).length} of ${cells.length} tiles placed`}</span><small>Select any tile to rotate it. Drag board tiles to move them or return them to your hand.</small></div>{selectedCell&&<button className="mobile-only" onClick={()=>returnBoardTileToHand(selectedCell)}>To hand</button>}<button disabled={!selectedCell&&selectedId===null} onClick={()=>rotateSelected(-1)}>Q ↺</button><button disabled={!selectedCell&&selectedId===null} onClick={()=>rotateSelected(1)}>R ↻</button><button className="primary" disabled={Object.keys(board).length!==cells.length} onClick={confirmPuzzle}>Confirm puzzle</button></div>:won&&<div className="confirm-bar puzzle-confirm puzzle-won"><div><span>Puzzle complete</span><small>{puzzle.word} is closed.</small></div><button className="primary" onClick={nextPuzzle}>Next puzzle</button></div>}
      </section>
      {internal?<aside className="right-rail"><section className="theme-panel"><p className="rail-label">VISUAL THEME</p><select value={themeId} onChange={e=>applyTheme(e.target.value)}>{THEMES.map(theme=><option key={theme.id} value={theme.id}>{theme.name}</option>)}</select><p>Inspired palettes; adjust any color below.</p></section><section className="play-palette"><p className="rail-label">COLORS</p><div><label><input type="color" value={tileColor} onChange={e=>setTileColor(e.target.value)}/>Tile</label><label><input type="color" value={surfaceColor} onChange={e=>setSurfaceColor(e.target.value)}/>Ground</label><label><input type="color" value={panelColor} onChange={e=>setPanelColor(e.target.value)}/>Panel</label><label><input type="color" value={lineColor} onChange={e=>setLineColor(e.target.value)}/>Line</label><label><input type="color" value={accentColor} onChange={e=>setAccentColor(e.target.value)}/>Accent</label><label><input type="color" value={voidColor} onChange={e=>setVoidColor(e.target.value)}/>Void</label>{palette.map(item=><label key={item.key}><input type="color" value={wordColors[item.key]} onChange={e=>setWordColors(colors=>({...colors,[item.key]:e.target.value}))}/>{item.label}</label>)}</div></section></aside>:<aside className="found-panel"><section className="featured-puzzles"><div><p className="rail-label">PUZZLES</p><span>{completedWords.size} completed</span></div><div className="featured-grid">{FEATURED_PUZZLES.map(word=>{const index=PUZZLES.findIndex(item=>item.word===word),complete=completedWords.has(word);return <button key={word} className={`${activePuzzle===index?"active":""} ${complete?"complete":""}`} onClick={()=>startPuzzle(index)}><span>{word}</span>{complete&&<b aria-label="Complete">✓</b>}</button>;})}</div></section><section className="found-words-section"><div className="found-header"><p className="rail-label">FOUND WORDS</p><span>{foundWords.length} found</span></div><div className="found-list">{foundWords.length?foundWords.map((item,i)=><b key={`${item.word}-${i}`} style={{borderColor:colorForLength(item.word.length)}}>{item.word} {item.points}</b>):<p>No words yet.</p>}</div></section></aside>}
      {internal&&<section className="word-tray"><div><p className="rail-label">FOUND WORDS</p><span>{foundWords.length} found</span></div><div className="bottom-words">{foundWords.length?foundWords.map((item,i)=><b key={`${item.word}-${i}`} style={{borderColor:colorForLength(item.word.length)}}>{item.word} {item.points}</b>):<p>No words yet.</p>}</div></section>}
    </div>}
    {showInstructions&&<div className="modal-backdrop"><div className="instructions-modal"><button className="modal-close" aria-label="Close instructions" onClick={()=>setShowInstructions(false)}>×</button><p className="step">HOW TO PLAY</p><h2>Close the puzzle</h2><div className="instruction-copy"><p>Place all seven tiles on the board. The lines on the tiles create closed sections. To win, enclose exactly the letters in the puzzle's title (in any order).</p><p>All other enclosed spaces must contain a real word, just one letter, or be empty. Spaces open to the edge can hold anything.</p><p>Move and rotate the tiles as much as you like. When you've placed all seven in a proper configuration, use the checkmark to confirm.</p></div><button className="primary" onClick={()=>setShowInstructions(false)}>Got it</button></div></div>}
    {showPuzzleSelector&&<div className="modal-backdrop mobile-puzzle-backdrop"><div className="mobile-puzzle-modal"><button className="modal-close" aria-label="Close puzzle list" onClick={()=>setShowPuzzleSelector(false)}>×</button><p className="step">PUZZLES</p><h2>Choose a puzzle</h2><div className="mobile-puzzle-list">{FEATURED_PUZZLES.map(word=>{const index=PUZZLES.findIndex(item=>item.word===word),complete=completedWords.has(word);return <button key={word} className={`${activePuzzle===index?"active":""} ${complete?"complete":""}`} onClick={()=>{startPuzzle(index);setShowPuzzleSelector(false);}}><span>{word}</span>{complete&&<b aria-label="Complete">✓</b>}</button>;})}</div></div></div>}
    {pending&&<div className="modal-backdrop"><div className={`word-modal ${flash?"shake":""}`}><p className="step">CLOSED SECTION{pending.filter(c=>c.words.length!==1).length>1?"S":""}</p><h2>Name the word{pending.filter(c=>c.words.length!==1).length>1?"s":""}.</h2>{pending.map((c,i)=>c.words.length===1?null:<div className="word-entry" key={i}><div className="letters">{c.letters.map((l,j)=><span key={j}>{l}</span>)}</div>{finder&&<p className="hints">Possible: {c.words.slice(0,8).join(" · ")}</p>}<input autoFocus={entries.findIndex((_,j)=>pending[j].words.length!==1)===i} value={entries[i]} onChange={e=>setEntries(x=>x.map((v,j)=>j===i?e.target.value.toUpperCase():v))} onKeyDown={e=>{if(e.key==="Enter")submitWords();}} placeholder="Type a valid anagram"/></div>)}<div className="modal-actions"><button className="quiet" onClick={()=>setPending(null)}>Back to placement</button><button className="primary" onClick={submitWords}>Submit & score</button></div></div></div>}
    {dragVisual&&(()=>{const tile=hand.find(item=>item.id===dragVisual.tileId)??Object.values(board).find(item=>item.id===dragVisual.tileId),pattern=tile&&getPattern(tile.patternId);return tile&&pattern?<div className="tile-drag-follow" style={{left:dragVisual.x,top:dragVisual.y,width:dragVisual.size,height:dragVisual.size}}><TileFace tile={tile} pattern={pattern} geometry={geometries[pattern.id]} hidden={hintHidden(tile)}/></div>:null;})()}
  </main>;
}
