import { useCallback, useEffect, useMemo, useRef, useState, type CSSProperties } from "react";
import { analyzePattern, cellsForSide, curvePath, DIRS, HEX, keyOf, PATTERNS, Pattern, PatternGeometry, shuffle, signature, Tile } from "./game";
import generatedTemplates from "./puzzle-calibration.json";
import sideBonusRound from "./side-bonus-round-1.json";
import sideBonusRoundTwo from "./side-bonus-round-2.json";
import sideBonusRoundThree from "./side-bonus-round-3.json";
import countriesExpanded from "./countries-expanded.json";
import countryVocabulary from "./country-vocabulary.json";
import fruitsExpanded from "./fruits-expanded.json";
import fruitVocabulary from "./fruit-vocabulary.json";
import tutorialPuzzles from "./tutorial-puzzles.json";
import "./globals.css";

type Placed = Tile;
type Preview = { cell:string; tileId:number; rotation:number };
type Component = { nodes:string[]; letters:string[]; closed:boolean; dead:boolean; touched:boolean; valid:boolean; words:string[] };
type Analysis = { components:Component[]; nodeStatus:Record<string,"affected"|"closed"|"invalid"|"dead">; valid:boolean; closed:Component[] };
type HistoryItem = { turn:number; words:string[]; wordPoints:number[]; points:number };
type WordColors = { one:string; two:string; three:string; four:string; five:string; six:string; sevenPlus:string };
type Theme = { id:string; name:string; surface:string; panel:string; tile:string; line:string; accent:string; void:string; words:WordColors; ink?:string; muted?:string; border?:string; invalid?:string; affected?:string; backdrop?:string; themeWord?:string };
type Difficulty="easy"|"medium"|"hard";
type PuzzleSpec={word:string;tier:Difficulty;template:number;duplicateClues:number;totalLetters:number;presetLetters?:string[][];initialRotations?:number[];setId?:string;themeId?:"countries"|"fruits";variant?:"natural"|"expanded";lesson?:string;lessonText?:string};
type PuzzleTemplate={patterns:string[];solutionRotations:number[];targetSlots:[number,number][];safeRegions:number[][];centerClues?:[number,number,number][];centerConstraint?:boolean;metrics:{centerPattern:string;centerPatternCopies:number;targetUsesCenter:boolean;targetTileCount:number;targetComponentSize:number}};
type CompletedBoardSnapshot={word:string;board:Record<string,Placed>;fills:Record<string,Record<number,string>>;lineColor:string;tileColor:string;voidColor:string;targetColor:string;completedAt:string};
type DiscoveredWord={word:string;puzzle:string;foundAt:string;themed?:boolean};
type SavedPuzzleState={version:1;activePuzzle:number;board:Record<string,Placed>;hand:Tile[];handSlots:Record<number,number>;handSlotCount:number;selectedId:number|null;selectedCell:string|null;score:number;turn:number;history:HistoryItem[];closedNodes:Record<string,number>;gameOver:boolean;won:boolean;hintMode:boolean;completedWords:string[];completedBoards?:Record<string,CompletedBoardSnapshot>;discoveredWords?:DiscoveredWord[];bonusPuzzleWords?:string[];hasSeenSuperTile?:boolean;updatedAt:string};

const TUTORIAL_MODE=window.location.pathname.replace(/\/+$/,"").endsWith("/how");
const STORAGE_KEY=TUTORIAL_MODE?"twiddler:tutorial-state:v2":"twiddler:puzzle-state:v3";

const FALLBACK_FREQ="EEEEEEEEEEEEAAAAAAAAAIIIIIIIIIOOOOOOOONNNNNNRRRRRRTTTTTTLLLLSSSSUUUUDDDDGGGBBCCMMPPFFHHVVWWYYKJXQZ";
const SCRABBLE_COUNTS:Record<string,number>={A:9,B:2,C:2,D:4,E:12,F:2,G:3,H:2,I:9,J:1,K:1,L:4,M:2,N:6,O:8,P:2,Q:1,R:6,S:4,T:6,U:4,V:2,W:2,X:1,Y:2,Z:1};
const SHORT_WORDS=["A","I","AA","AB","AD","AE","AG","AH","AI","AL","AM","AN","AR","AS","AT","AW","AX","AY","BA","BE","BI","BO","BY","DA","DE","DO","ED","EF","EH","EL","EM","EN","ER","ES","ET","EW","EX","FA","FE","GI","GO","GU","HA","HE","HI","HM","HO","ID","IF","IN","IO","IS","IT","JA","JO","KA","KI","KO","KY","LA","LI","LO","MA","ME","MI","MM","MO","MU","MY","NA","NE","NG","NI","NO","NU","OD","OE","OF","OH","OI","OM","ON","OP","OR","OS","OU","OW","OX","OY","PA","PE","PI","PO","QI","RE","SH","SI","SO","TA","TE","TI","TO","UH","UM","UN","UP","US","UT","WE","WO","XI","XU","YA","YE","YO","ZA"];
const THEMES:Theme[]=[
  {id:"talavera",name:"Talavera Courtyard",surface:"#f1eadc",panel:"#e7ddcb",tile:"#fff8e8",line:"#b65b3d",accent:"#2f6390",void:"#d8d0c2",words:{one:"#8aa9a1",two:"#2a7f7a",three:"#d8a51d",four:"#c9543f",five:"#608449",six:"#d48642",sevenPlus:"#376b85"}},
  {id:"iznik",name:"İznik Evening",surface:"#eeeae3",panel:"#e0e4e7",tile:"#fffaf0",line:"#304f82",accent:"#b6484f",void:"#d7d9dc",words:{one:"#8a9eb5",two:"#2d8c91",three:"#365c9a",four:"#705083",five:"#b6484f",six:"#587d9d",sevenPlus:"#80627f"}},
  {id:"mediterranean",name:"Mediterranean Grove",surface:"#eee9df",panel:"#e3ddcf",tile:"#faf6eb",line:"#626b50",accent:"#a54d3d",void:"#d5d0c5",words:{one:"#a3a58e",two:"#77804e",three:"#c2763f",four:"#a54d3d",five:"#60777a",six:"#a98251",sevenPlus:"#875b50"}},
  {id:"castilian",name:"Castilian Sky",surface:"#edf0ee",panel:"#e0e6e6",tile:"#fcfdfb",line:"#5e568c",accent:"#c99b18",void:"#dce1e1",words:{one:"#8baaa5",two:"#d9b633",three:"#27928e",four:"#6d9a4b",five:"#d46a52",six:"#6486a7",sevenPlus:"#82639a"}},
  {id:"zellige",name:"Zellige Garden",surface:"#eee9dc",panel:"#e4dccb",tile:"#fff9e9",line:"#376b5a",accent:"#b47a25",void:"#d7d0c0",words:{one:"#83a49b",two:"#238b88",three:"#386a9a",four:"#d0a23a",five:"#a44f42",six:"#55805d",sevenPlus:"#665b8c"}},
  {id:"inkjet-4",name:"Inkjet Mischief IV",surface:"#e8f2f7",panel:"#d9e9ef",tile:"#fffefe",line:"#172b38",accent:"#00bfa5",void:"#d2dfe5",ink:"#172b38",muted:"#607481",border:"#8fa6b2",invalid:"#e83f52",affected:"#b7ead2",themeWord:"#a8ddd7",words:{one:"#b6cfd8",two:"#69ccdc",three:"#9fa9ee",four:"#f3b16c",five:"#82d5a4",six:"#efd064",sevenPlus:"#7eb2e5"}},
];
const DEFAULT_THEME=THEMES.find(theme=>theme.id==="inkjet-4")!;
const PUZZLE_TEMPLATES=generatedTemplates as PuzzleTemplate[];
const APPLE_TUTORIAL:PuzzleSpec={word:"APPLE",tier:"easy",template:57,duplicateClues:0,totalLetters:7,presetLetters:[
  ["Q","","","",""],
  ["","","","","P"],
  ["","","P","",""],
  ["A","","",""],
  ["Z","","","",""],
  ["","","","E",""],
  ["","","L","","",""]
]};
const PUZZLES:PuzzleSpec[]=[
  ...(tutorialPuzzles as PuzzleSpec[]),
  ...(fruitsExpanded as PuzzleSpec[]),
  ...(countriesExpanded as PuzzleSpec[]),
  APPLE_TUTORIAL,
  {word:"STAR",tier:"easy",template:0,duplicateClues:6,totalLetters:14},{word:"MOON",tier:"easy",template:1,duplicateClues:6,totalLetters:15},{word:"PEAR",tier:"easy",template:2,duplicateClues:5,totalLetters:15},{word:"FROG",tier:"easy",template:3,duplicateClues:5,totalLetters:16},{word:"MAPLE",tier:"easy",template:4,duplicateClues:6,totalLetters:16},{word:"BEACH",tier:"easy",template:5,duplicateClues:5,totalLetters:17},{word:"TIGER",tier:"easy",template:6,duplicateClues:5,totalLetters:17},{word:"COOKIE",tier:"easy",template:7,duplicateClues:6,totalLetters:18},{word:"PLANET",tier:"easy",template:8,duplicateClues:5,totalLetters:18},{word:"RAINBOW",tier:"easy",template:9,duplicateClues:5,totalLetters:19},
  {word:"WAVE",tier:"medium",template:10,duplicateClues:3,totalLetters:19},{word:"MINT",tier:"medium",template:11,duplicateClues:3,totalLetters:20},{word:"PLUM",tier:"medium",template:12,duplicateClues:2,totalLetters:21},{word:"CORAL",tier:"medium",template:13,duplicateClues:3,totalLetters:21},{word:"ROBIN",tier:"medium",template:14,duplicateClues:2,totalLetters:22},{word:"HONEY",tier:"medium",template:15,duplicateClues:3,totalLetters:22},{word:"CASTLE",tier:"medium",template:16,duplicateClues:3,totalLetters:23},{word:"TURTLE",tier:"medium",template:17,duplicateClues:3,totalLetters:23},{word:"COMPASS",tier:"medium",template:18,duplicateClues:3,totalLetters:24},{word:"OCTOPUS",tier:"medium",template:19,duplicateClues:2,totalLetters:24},
  {word:"KITE",tier:"hard",template:20,duplicateClues:1,totalLetters:23},{word:"LIME",tier:"hard",template:21,duplicateClues:1,totalLetters:24},{word:"MOSS",tier:"hard",template:22,duplicateClues:1,totalLetters:24},{word:"BRICK",tier:"hard",template:23,duplicateClues:1,totalLetters:25},{word:"GRAPE",tier:"hard",template:24,duplicateClues:1,totalLetters:26},{word:"FLAME",tier:"hard",template:25,duplicateClues:0,totalLetters:26},{word:"JUNGLE",tier:"hard",template:26,duplicateClues:1,totalLetters:27},{word:"RABBIT",tier:"hard",template:27,duplicateClues:1,totalLetters:27},{word:"LANTERN",tier:"hard",template:28,duplicateClues:1,totalLetters:28},{word:"DOLPHIN",tier:"hard",template:29,duplicateClues:0,totalLetters:28},
  {word:"LEMON",tier:"easy",template:30,duplicateClues:5,totalLetters:17},{word:"PRETZEL",tier:"hard",template:31,duplicateClues:1,totalLetters:28},{word:"TRACTOR",tier:"hard",template:32,duplicateClues:1,totalLetters:28},{word:"MERMAID",tier:"hard",template:33,duplicateClues:1,totalLetters:28},
  {word:"SHARK",tier:"medium",template:34,duplicateClues:4,totalLetters:21},{word:"OTTER",tier:"medium",template:35,duplicateClues:5,totalLetters:22},{word:"KOALA",tier:"medium",template:36,duplicateClues:5,totalLetters:22},{word:"GARDEN",tier:"medium",template:37,duplicateClues:4,totalLetters:23},{word:"PEBBLE",tier:"medium",template:38,duplicateClues:5,totalLetters:23},{word:"CICADA",tier:"medium",template:39,duplicateClues:5,totalLetters:24},{word:"PENGUIN",tier:"medium",template:40,duplicateClues:4,totalLetters:24},{word:"GIRAFFE",tier:"medium",template:41,duplicateClues:4,totalLetters:24},{word:"HAMSTER",tier:"medium",template:42,duplicateClues:3,totalLetters:25},{word:"CHICKEN",tier:"medium",template:43,duplicateClues:4,totalLetters:25},
  {word:"WOLF",tier:"medium",template:44,duplicateClues:4,totalLetters:26},{word:"JADE",tier:"medium",template:45,duplicateClues:4,totalLetters:25},{word:"ECHO",tier:"medium",template:46,duplicateClues:3,totalLetters:25},{word:"SQUID",tier:"medium",template:47,duplicateClues:4,totalLetters:27},{word:"MANGO",tier:"medium",template:48,duplicateClues:4,totalLetters:26},{word:"COBRA",tier:"medium",template:49,duplicateClues:3,totalLetters:26},{word:"RAVEN",tier:"medium",template:50,duplicateClues:4,totalLetters:27},{word:"BADGER",tier:"medium",template:51,duplicateClues:3,totalLetters:27},{word:"WALNUT",tier:"medium",template:52,duplicateClues:3,totalLetters:27},{word:"RACCOON",tier:"medium",template:53,duplicateClues:4,totalLetters:27},
  {word:"LYNX",tier:"medium",template:54,duplicateClues:3,totalLetters:25},{word:"PEAK",tier:"medium",template:55,duplicateClues:4,totalLetters:25},{word:"SWAN",tier:"medium",template:56,duplicateClues:4,totalLetters:26},{word:"HORSE",tier:"medium",template:57,duplicateClues:4,totalLetters:26},{word:"PEACH",tier:"medium",template:58,duplicateClues:4,totalLetters:26},{word:"STORM",tier:"medium",template:59,duplicateClues:3,totalLetters:27},{word:"PANDA",tier:"medium",template:60,duplicateClues:4,totalLetters:27},{word:"KITTEN",tier:"medium",template:61,duplicateClues:4,totalLetters:27},{word:"ROCKET",tier:"medium",template:62,duplicateClues:3,totalLetters:28},{word:"ORCHARD",tier:"medium",template:63,duplicateClues:3,totalLetters:28},
  {word:"FERN",tier:"medium",template:64,duplicateClues:3,totalLetters:26},{word:"DOVE",tier:"medium",template:65,duplicateClues:4,totalLetters:26},{word:"RUBY",tier:"medium",template:66,duplicateClues:3,totalLetters:26},{word:"GECKO",tier:"medium",template:67,duplicateClues:4,totalLetters:27},{word:"PLANT",tier:"medium",template:68,duplicateClues:3,totalLetters:27},{word:"BREAD",tier:"medium",template:69,duplicateClues:4,totalLetters:27},{word:"WHALE",tier:"medium",template:70,duplicateClues:3,totalLetters:27},{word:"MAGNET",tier:"medium",template:71,duplicateClues:3,totalLetters:28},{word:"COYOTE",tier:"medium",template:72,duplicateClues:4,totalLetters:28},{word:"MONARCH",tier:"medium",template:73,duplicateClues:3,totalLetters:28},
  {word:"COZY",tier:"medium",template:74,duplicateClues:3,totalLetters:26},{word:"BOOK",tier:"medium",template:75,duplicateClues:4,totalLetters:26},{word:"CAKE",tier:"medium",template:76,duplicateClues:3,totalLetters:26},{word:"GLOW",tier:"medium",template:77,duplicateClues:3,totalLetters:26},{word:"PIZZA",tier:"medium",template:78,duplicateClues:4,totalLetters:27},{word:"DONUT",tier:"medium",template:79,duplicateClues:3,totalLetters:27},{word:"DISCO",tier:"medium",template:80,duplicateClues:4,totalLetters:27},{word:"MAGIC",tier:"medium",template:81,duplicateClues:3,totalLetters:27},{word:"DREAM",tier:"medium",template:82,duplicateClues:3,totalLetters:27},{word:"BUBBLE",tier:"medium",template:83,duplicateClues:4,totalLetters:28},{word:"PICKLE",tier:"medium",template:84,duplicateClues:3,totalLetters:28},{word:"WAFFLE",tier:"medium",template:85,duplicateClues:4,totalLetters:28},{word:"SUNSET",tier:"medium",template:86,duplicateClues:3,totalLetters:28},{word:"CIRCUS",tier:"medium",template:87,duplicateClues:3,totalLetters:28},{word:"COFFEE",tier:"medium",template:88,duplicateClues:4,totalLetters:28},{word:"CUPCAKE",tier:"medium",template:89,duplicateClues:3,totalLetters:28},{word:"BALLOON",tier:"medium",template:90,duplicateClues:4,totalLetters:28},{word:"SPARKLE",tier:"medium",template:91,duplicateClues:3,totalLetters:28},{word:"PANCAKE",tier:"medium",template:92,duplicateClues:3,totalLetters:28},{word:"FESTIVE",tier:"medium",template:93,duplicateClues:3,totalLetters:28},
  ...(sideBonusRound as PuzzleSpec[]),
  ...(sideBonusRoundTwo as PuzzleSpec[]),
  ...(sideBonusRoundThree as PuzzleSpec[]),
];
const FEATURED_SET_ID=TUTORIAL_MODE?"tutorial":"fruits-overlap-expanded-v3";
const FEATURED_PUZZLES=TUTORIAL_MODE?["ALPACA","BISON","COYOTE"]:["APPLE","PEACH","LIME","ORANGE","BANANA","CHERRY","APRICOT"];
const featuredPuzzleIndex=(word:string)=>PUZZLES.findIndex(puzzle=>puzzle.setId===FEATURED_SET_ID&&puzzle.word===word);
const DEFAULT_PUZZLE_INDEX=featuredPuzzleIndex(FEATURED_PUZZLES[0]);
const THEME_WORDS={countries:countryVocabulary.accepted,fruits:fruitVocabulary.accepted} as const;
const TARGET_COLORS:Record<string,string>={APPLE:"#f4d64e",CAKE:"#f4d64e",SHARK:"#55c3b8",SQUID:"#8585e8",DOVE:"#8ed89f",GECKO:"#b9dc52",TRACTOR:"#f0a44f",MERMAID:"#c890e8",MUSIC:"#62c7da",TOAST:"#f2b84b",CANDLE:"#f4d45a",RIVER:"#5dc6a5",JELLY:"#a98bea",BRIGHT:"#8fd451",PAPER:"#71aee8",JUICE:"#f0c84f",RADIO:"#65b7e8",POCKET:"#8dcf68",LIGHT:"#f3dc62",CANDY:"#a98bea",GROOVE:"#59c5ad",TABLE:"#eea85c",CHIME:"#f0c84f",QUILT:"#8585e8",MELODY:"#59c5ad",COCOA:"#d69255",PUZZLE:"#a98bea",POPCORN:"#f3dc62",SUNBEAM:"#71aee8",BANANA:"#55c3b8",CHERRY:"#8585e8",PEACH:"#f2a36f",LIME:"#9ed64b",ORANGE:"#ef8f3e",APRICOT:"#71aee8",ALPACA:"#f4d64e",BISON:"#55c3b8",COYOTE:"#8585e8",CHILE:"#f2a36f",JAPAN:"#f4d64e",BRAZIL:"#9ed64b",CANADA:"#55c3b8",FRANCE:"#8585e8",ICELAND:"#71aee8",JAMAICA:"#c890e8"};
Object.assign(TARGET_COLORS,{APPLE:"#ffd447",PEACH:"#ff9f76",LIME:"#8bdd5a",ORANGE:"#ff8a3d",BANANA:"#f7e65c",CHERRY:"#ec6fa1",APRICOT:"#61c8e8",ALPACA:"#ffd447",BISON:"#52c8c2",COYOTE:"#9b8ff0"});
const SOLUTION_CELL_KEYS=["-1,0","-1,1","0,-1","0,0","0,1","1,-1","1,0"];
const SUPERTILE_OFFSETS:[[number,number],...Array<[number,number]>]=[[0,0],[2,1],[-1,3],[-3,2],[-2,-1],[1,-3],[3,-2]];
const colorKeyForLength=(length:number):keyof WordColors=>length===1?"one":length===2?"two":length===3?"three":length===4?"four":length===5?"five":length===6?"six":"sevenPlus";
function paletteForWord(word:string){const words={...DEFAULT_THEME.words},targetColor=TARGET_COLORS[word]??words[colorKeyForLength(word.length)];return {line:DEFAULT_THEME.line,words,targetColor};}
const DECOY_POOL="EEEEEEEEAAAAAAAIIIIIIIOOOOOOONNNNNNRRRRRRTTTTTTLLLLSSSSUUUUDDDDGGGBBCCMMPPFFHHVVWWYYKJXQZ";
const parsePairs=(value:string)=>{const out:[number,number][]=[];for(const part of value.split(",")){const m=part.trim().match(/^([1-6])\s*[-–:]\s*([1-6])$/);if(!m||m[1]===m[2])return null;out.push([+m[1],+m[2]]);}return out;};

function TileFace({tile,pattern,geometry,status={},fills={},hidden={},preview=false,showLetters=true}:{tile:Tile;pattern:Pattern;geometry:PatternGeometry;status?:Record<number,string>;fills?:Record<number,string>;hidden?:Record<number,boolean>;preview?:boolean;showLetters?:boolean}){
  const offsetCenter=pattern.id==="offset"?geometry.regions.find(region=>region.ports.length===4):null;
  return <svg width="100" height="100" viewBox="0 0 100 100" className={preview?"tile-svg preview":"tile-svg"} aria-hidden="true">
    <defs><clipPath id="tile-hex-clip"><polygon points={HEX.map(p=>p.join(",")).join(" ")} /></clipPath></defs>
    <polygon points={HEX.map(p=>p.join(",")).join(" ")} className="tile-paper" />
    <g transform={`rotate(${tile.rotation*60} 50 50)`} clipPath="url(#tile-hex-clip)">
      {geometry.regions.map((region)=><path key={region.id} d={region.mask} className={`region-fill ${status[region.id]||""}`} style={fills[region.id]?{fill:fills[region.id]}:undefined} />)}
      {pattern.pairs.map((pair,i)=><path key={i} d={curvePath(pair)} className="wall" />)}
      {showLetters&&geometry.regions.map((region)=>{if(!tile.letters[region.id]||hidden[region.id])return null;let x=region.cx,y=region.cy;if(offsetCenter?.id===region.id){x=50+(x-50)*.52;y=50+(y-50)*.52;}return <text key={`l${region.id}`} x={x} y={y+4.2} transform={preview?undefined:`rotate(${-tile.rotation*60} ${x} ${y})`} className="letter">{tile.letters[region.id]}</text>;})}
    </g>
  </svg>;
}

function BoardThumbnail({snapshot,patterns,geometries,className="",hasBonus=false}:{snapshot:CompletedBoardSnapshot;patterns:Pattern[];geometries:Record<string,PatternGeometry>;className?:string;hasBonus?:boolean}){return <svg className={`completion-thumbnail ${className}`} viewBox="200.3 211 299.4 278" style={{"--tile-line":snapshot.lineColor,"--green":snapshot.lineColor,"--white":snapshot.tileColor,"--void":snapshot.voidColor} as CSSProperties} aria-label={`${snapshot.word} completed board`}>{cellsForSide(2).map(({q,r})=>{const cell=keyOf(q,r),tile=snapshot.board[cell];if(!tile)return null;const x=350+79.7*(q+r/2),y=350+69*r,pattern=patterns.find(item=>item.id===tile.patternId);return pattern?<g key={cell} transform={`translate(${x-50} ${y-50})`}><TileFace tile={tile} pattern={pattern} geometry={geometries[tile.patternId]} fills={snapshot.fills[cell]||{}} showLetters={false}/></g>:null;})}{hasBonus&&<polygon className="theme-star" fill={snapshot.lineColor} stroke={snapshot.lineColor} points={starPoints(350,350,15)}/>}</svg>}

const starPoints=(cx:number,cy:number,outer=15,inner=6.5)=>Array.from({length:10},(_,index)=>{const angle=-Math.PI/2+index*Math.PI/5,radius=index%2?inner:outer;return `${cx+Math.cos(angle)*radius},${cy+Math.sin(angle)*radius}`;}).join(" ");
function SupertileSvg({snapshots,patterns,geometries,svgRef,bonusPuzzleWords}:{snapshots:CompletedBoardSnapshot[];patterns:Pattern[];geometries:Record<string,PatternGeometry>;svgRef:React.RefObject<SVGSVGElement|null>;bonusPuzzleWords:Set<string>}){return <svg ref={svgRef} className="super-tile-source" xmlns="http://www.w3.org/2000/svg" viewBox="8 8 684 684" width="1200" height="1200"><style>{`.tile-paper{fill:var(--white);stroke:#20251f;stroke-width:1.25}.region-fill{fill:transparent}.wall{fill:none;stroke:var(--tile-line);stroke-width:4.5;stroke-linecap:round;stroke-linejoin:round}.theme-star{stroke-width:2}`}</style>{snapshots.map((snapshot,index)=>{const [oq,or]=SUPERTILE_OFFSETS[index],centerX=350+79.7*(oq+or/2),centerY=350+69*or;return <g key={snapshot.word} style={{"--tile-line":snapshot.lineColor,"--white":snapshot.tileColor,"--void":snapshot.voidColor} as CSSProperties}>{cellsForSide(2).map(({q,r})=>{const cell=keyOf(q,r),tile=snapshot.board[cell],pattern=tile&&patterns.find(item=>item.id===tile.patternId);if(!tile||!pattern)return null;const globalQ=q+oq,globalR=r+or,x=350+79.7*(globalQ+globalR/2),y=350+69*globalR;return <g key={`${snapshot.word}-${cell}`} transform={`translate(${x-50} ${y-50})`}><TileFace tile={tile} pattern={pattern} geometry={geometries[tile.patternId]} fills={snapshot.fills[cell]||{}} showLetters={false}/></g>;})}{bonusPuzzleWords.has(snapshot.word)&&<polygon className="theme-star" fill={snapshot.lineColor} stroke={snapshot.lineColor} points={starPoints(centerX,centerY,15)}/>}</g>;})}</svg>}

function RotateIcon({direction}:{direction:"left"|"right"}){return direction==="left"?<svg className="control-icon" viewBox="0 0 24 24" aria-hidden="true"><path d="M20 15a8 8 0 0 0-8-10H7"/><path d="m10 2-3 3 3 3"/></svg>:<svg className="control-icon" viewBox="0 0 24 24" aria-hidden="true"><path d="M4 15a8 8 0 0 1 8-10h5"/><path d="m14 2 3 3-3 3"/></svg>}
function HomeIcon(){return <svg className="control-icon home-icon" viewBox="0 0 24 24" aria-hidden="true"><path d="m3 11 9-8 9 8"/><path d="M5 10v10h14V10M9 20v-6h6v6"/></svg>}

export default function App(){
  const internal=false;
  const [tab,setTab]=useState<"play"|"lab">("play");
  const [patterns,setPatterns]=useState<Pattern[]>(PATTERNS);
  const [deckSize,setDeckSize]=useState(7);
  const [boardSide,setBoardSide]=useState(2);
  const [startingHand,setStartingHand]=useState(7);
  const [letterSpawnRate,setLetterSpawnRate]=useState(60);
  const [wordColors,setWordColors]=useState<WordColors>(DEFAULT_THEME.words);
  const [lineColor,setLineColor]=useState(DEFAULT_THEME.line);
  const [voidColor,setVoidColor]=useState(DEFAULT_THEME.void);
  const [themeId,setThemeId]=useState(DEFAULT_THEME.id);
  const [surfaceColor,setSurfaceColor]=useState(DEFAULT_THEME.surface);
  const [panelColor,setPanelColor]=useState(DEFAULT_THEME.panel);
  const [tileColor,setTileColor]=useState(DEFAULT_THEME.tile);
  const [accentColor,setAccentColor]=useState(DEFAULT_THEME.accent);
  const [configDirty,setConfigDirty]=useState(false);
  const [configLoaded,setConfigLoaded]=useState(true);
  const [dictionaryLoaded,setDictionaryLoaded]=useState(false);
  const geometries=useMemo(()=>Object.fromEntries(patterns.map(p=>[p.id,analyzePattern(p)])),[patterns]);
  const cells=useMemo(()=>cellsForSide(boardSide),[boardSide]);
  const boardKeys=useMemo(()=>new Set(cells.map(({q,r})=>keyOf(q,r))),[cells]);
  const [words,setWords]=useState<string[]>([]);
  const [exact,setExact]=useState<Map<string,string[]>>(new Map());
  const [letterPool,setLetterPool]=useState(FALLBACK_FREQ);
  const [board,setBoard]=useState<Record<string,Placed>>({});
  const [deck,setDeck]=useState<Tile[]>([]);
  const [hand,setHand]=useState<Tile[]>([]);
  const [handSlots,setHandSlots]=useState<Record<number,number>>({});
  const [handSlotCount,setHandSlotCount]=useState(0);
  const [newId,setNewId]=useState<number|null>(null);
  const [selectedId,setSelectedId]=useState<number|null>(null);
  const [selectedCell,setSelectedCell]=useState<string|null>(null);
  const [draggingId,setDraggingId]=useState<number|null>(null);
  const [dragVisual,setDragVisual]=useState<{tileId:number;x:number;y:number;size:number}|null>(null);
  const [preview,setPreview]=useState<Preview|null>(null);
  const [score,setScore]=useState(0);
  const [,setDestroyedCount]=useState(0);
  const [turn,setTurn]=useState(1);
  const [history,setHistory]=useState<HistoryItem[]>([]);
  const [closedNodes,setClosedNodes]=useState<Record<string,number>>({});
  const [warn,setWarn]=useState(false);
  const [finder,setFinder]=useState(true);
  const [chooseWord,setChooseWord]=useState(false);
  const [showInstructions,setShowInstructions]=useState(false);
  const [flash,setFlash]=useState(false);
  const [pending,setPending]=useState<Component[]|null>(null);
  const [entries,setEntries]=useState<string[]>([]);
  const [gameOver,setGameOver]=useState(false);
  const [won,setWon]=useState(false);
  const [hintMode,setHintMode]=useState(false);
  const [activePuzzle,setActivePuzzle]=useState(DEFAULT_PUZZLE_INDEX);
  const [completedWords,setCompletedWords]=useState<Set<string>>(()=>new Set());
  const [completedBoards,setCompletedBoards]=useState<Record<string,CompletedBoardSnapshot>>({});
  const [discoveredWords,setDiscoveredWords]=useState<DiscoveredWord[]>([]);
  const [bonusPuzzleWords,setBonusPuzzleWords]=useState<Set<string>>(()=>new Set());
  const [submissionMessage,setSubmissionMessage]=useState("");
  const [confirmNotice,setConfirmNotice]=useState("");
  const [storageReady,setStorageReady]=useState(false);
  const [showPuzzleSelector,setShowPuzzleSelector]=useState(false);
  const [showFoundWords,setShowFoundWords]=useState(false);
  const [showSuperTile,setShowSuperTile]=useState(false);
  const [hasSeenSuperTile,setHasSeenSuperTile]=useState(false);
  const [superTileImage,setSuperTileImage]=useState("");
  const boardSvgRef=useRef<SVGSVGElement|null>(null);
  const superTileSvgRef=useRef<SVGSVGElement|null>(null);
  const restoreStartedRef=useRef(false);
  const dragGhostRef=useRef<HTMLElement|null>(null);
  const dropAcceptedRef=useRef(false);
  const suppressBoardClickRef=useRef(false);
  const confirmNoticeTimerRef=useRef<ReturnType<typeof setTimeout>|null>(null);

  function showConfirmNotice(message:string){if(confirmNoticeTimerRef.current)clearTimeout(confirmNoticeTimerRef.current);setConfirmNotice(message);confirmNoticeTimerRef.current=setTimeout(()=>{setConfirmNotice("");confirmNoticeTimerRef.current=null;},1700);}
  useEffect(()=>()=>{if(confirmNoticeTimerRef.current)clearTimeout(confirmNoticeTimerRef.current);},[]);

  useEffect(()=>{fetch(new URL("../words.txt",window.location.href)).then(r=>{if(!r.ok)throw new Error(`Dictionary request failed: ${r.status}`);return r.text();}).then(text=>{const longWords=text.split(/\s+/).filter(w=>w.length>=3),list=[...SHORT_WORDS,...longWords];setWords(list);const map=new Map<string,string[]>(),counts:Record<string,number>={};for(const word of list){const sig=signature(word);const arr=map.get(sig)||[];if(arr.length<30)arr.push(word);map.set(sig,arr);}for(const word of longWords)for(const c of word)counts[c]=(counts[c]||0)+1;setExact(map);const total=Object.values(counts).reduce((a,b)=>a+b,0);let pool="";for(const c of "ABCDEFGHIJKLMNOPQRSTUVWXYZ"){const english=(counts[c]||0)/total,scrabble=SCRABBLE_COUNTS[c]/100,blended=(english+scrabble)/2;pool+=c.repeat(Math.max(1,Math.round(blended*1200)));}setLetterPool(pool);setDictionaryLoaded(true);}).catch(error=>{console.warn("Could not load puzzle dictionary",error);setDictionaryLoaded(true);});},[]);

  const randomLetter=useCallback(()=>letterPool[Math.floor(Math.random()*letterPool.length)]||"E",[letterPool]);
  const makeDeck=useCallback(()=>{let id=1;const counts=patterns.map(p=>Math.floor(deckSize*p.weight/100));while(counts.reduce((a,b)=>a+b,0)<deckSize){const i=counts.reduce((best,_,j)=>deckSize*patterns[j].weight/100-counts[j]>deckSize*patterns[best].weight/100-counts[best]?j:best,0);counts[i]++;}while(counts.reduce((a,b)=>a+b,0)>deckSize)counts[counts.indexOf(Math.max(...counts))]--;const cards:Tile[]=[];patterns.forEach((p,i)=>{for(let n=0;n<counts[i];n++){const letters=geometries[p.id].regions.map(()=>Math.random()*100<letterSpawnRate?randomLetter():"");if(!letters.some(Boolean))letters[Math.floor(Math.random()*letters.length)]=randomLetter();cards.push({id:id++,patternId:p.id,rotation:0,letters});}});return shuffle(cards);},[deckSize,patterns,geometries,randomLetter,letterSpawnRate]);

  const puzzle=PUZZLES[activePuzzle],puzzleTemplate=PUZZLE_TEMPLATES[puzzle.template];
  const activeThemeWords=useMemo(()=>puzzle.themeId?[...THEME_WORDS[puzzle.themeId]]:[],[puzzle.themeId]);
  const activeThemeBySignature=useMemo(()=>{const map=new Map<string,string[]>();for(const word of activeThemeWords){const sig=signature(word),matches=map.get(sig)||[];matches.push(word);map.set(sig,matches);}return map;},[activeThemeWords]);
  useEffect(()=>{const palette=paletteForWord(puzzle.word);setLineColor(palette.line);setWordColors(palette.words);},[puzzle.word]);
  function createPuzzleTiles(index:number){const spec=PUZZLES[index],template=PUZZLE_TEMPLATES[spec.template],tiles=template.patterns.map((patternId,i)=>({id:i+1,patternId,rotation:spec.initialRotations?.[i]??Math.floor(Math.random()*6),letters:spec.presetLetters?.[i]?[...spec.presetLetters[i]]:geometries[patternId].regions.map(()=>"")}));if(spec.presetLetters)return tiles;template.targetSlots.forEach(([tile,region],i)=>tiles[tile].letters[region]=spec.word[i]);template.centerClues?.forEach(([tile,region,letterIndex])=>tiles[tile].letters[region]=spec.word[letterIndex]);let seed=[...spec.word].reduce((n,c)=>((n*33+c.charCodeAt(0))>>>0),5381),random=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;};const slots=template.safeRegions.flatMap((regions,tile)=>regions.map(region=>({tile,region}))).filter(slot=>!tiles[slot.tile].letters[slot.region]&&(!template.centerConstraint||slot.region!==0||geometries[tiles[slot.tile].patternId].regions[0].ports.length<4));for(let i=slots.length-1;i>0;i--){const j=Math.floor(random()*(i+1));[slots[i],slots[j]]=[slots[j],slots[i]];}const rarity="ZQXJKVBPYGFWMUCLDRHSONITEA",unique=[...new Set(spec.word)].sort((a,b)=>rarity.indexOf(a)-rarity.indexOf(b)),extras=[...Array(spec.duplicateClues)].map((_,i)=>unique[i%unique.length]);while(extras.length<spec.totalLetters-spec.word.length-(template.centerClues?.length??0))extras.push(DECOY_POOL[Math.floor(random()*DECOY_POOL.length)]);slots.slice(0,extras.length).forEach((slot,i)=>tiles[slot.tile].letters[slot.region]=extras[i]);tiles.forEach((tile,i)=>{if(!tile.letters.some(Boolean)&&template.safeRegions[i][0]!==undefined)tile.letters[template.safeRegions[i][0]]=DECOY_POOL[Math.floor(random()*DECOY_POOL.length)];});return tiles;}
  function startPuzzle(index:number){const dealt=createPuzzleTiles(index);setActivePuzzle(index);setBoard({});setDeck([]);setHand(dealt);setHandSlots(Object.fromEntries(dealt.map((tile,i)=>[tile.id,i])));setHandSlotCount(dealt.length);setNewId(null);setSelectedId(dealt[0]?.id??null);setSelectedCell(null);setPreview(null);setScore(0);setDestroyedCount(0);setTurn(1);setHistory([]);setClosedNodes({});setPending(null);setGameOver(false);setWon(false);setHintMode(false);setSubmissionMessage("");setConfirmNotice("");setConfigDirty(false);setTab("play");}
  function selectPuzzle(index:number){const snapshot=completedBoards[PUZZLES[index].word];if(!snapshot){startPuzzle(index);return;}const restoredBoard=Object.fromEntries(Object.entries(snapshot.board).map(([cell,tile])=>[cell,{...tile,letters:[...tile.letters]}]));setActivePuzzle(index);setBoard(restoredBoard);setDeck([]);setHand([]);setHandSlots(Object.fromEntries(Object.values(restoredBoard).map(tile=>[tile.id,tile.id-1])));setHandSlotCount(7);setNewId(null);setSelectedId(null);setSelectedCell(null);setPreview(null);setScore(0);setDestroyedCount(0);setTurn(1);setHistory([]);setClosedNodes({});setPending(null);setGameOver(false);setWon(true);setHintMode(false);setSubmissionMessage("");setConfigDirty(false);setTab("play");}
  const newGame=useCallback(()=>startPuzzle(activePuzzle),[activePuzzle,geometries]);
  useEffect(()=>{if(!configLoaded||!dictionaryLoaded||!patterns.length||restoreStartedRef.current)return;restoreStartedRef.current=true;let restored=false;try{const saved=JSON.parse(localStorage.getItem(STORAGE_KEY)||"null") as SavedPuzzleState|null;if(saved?.version===1&&PUZZLES[saved.activePuzzle]&&Array.isArray(saved.hand)&&saved.board&&saved.handSlots){setActivePuzzle(saved.activePuzzle);setBoard(saved.board);setDeck([]);setHand(saved.hand);setHandSlots(saved.handSlots);setHandSlotCount(saved.handSlotCount||7);setSelectedId(saved.selectedId);setSelectedCell(saved.selectedCell);setScore(saved.score||0);setTurn(saved.turn||1);setHistory(saved.history||[]);setClosedNodes(saved.closedNodes||{});setGameOver(Boolean(saved.gameOver));setWon(Boolean(saved.won));setHintMode(Boolean(saved.hintMode));setCompletedWords(new Set(saved.completedWords||[]));setCompletedBoards(Object.fromEntries(Object.entries(saved.completedBoards||{}).map(([word,snapshot])=>{const index=PUZZLES.findIndex(item=>item.word===word);return [word,index>=0?createCompletedSnapshot(index,snapshot.board):snapshot];})));setDiscoveredWords(saved.discoveredWords||[]);setBonusPuzzleWords(new Set(saved.bonusPuzzleWords||saved.discoveredWords?.filter(item=>item.themed).map(item=>item.puzzle)||[]));setHasSeenSuperTile(Boolean(saved.hasSeenSuperTile));restored=true;}}catch(error){console.warn("Could not restore saved puzzle progress",error);}if(!restored)startPuzzle(activePuzzle);setStorageReady(true);},[configLoaded,dictionaryLoaded,patterns.length]);
  useEffect(()=>{if(!storageReady)return;const saved:SavedPuzzleState={version:1,activePuzzle,board,hand,handSlots,handSlotCount,selectedId,selectedCell,score,turn,history,closedNodes,gameOver,won,hintMode,completedWords:[...completedWords],completedBoards,discoveredWords,bonusPuzzleWords:[...bonusPuzzleWords],hasSeenSuperTile,updatedAt:new Date().toISOString()};try{localStorage.setItem(STORAGE_KEY,JSON.stringify(saved));}catch(error){console.warn("Could not save puzzle progress",error);}},[storageReady,activePuzzle,board,hand,handSlots,handSlotCount,selectedId,selectedCell,score,turn,history,closedNodes,gameOver,won,hintMode,completedWords,completedBoards,discoveredWords,bonusPuzzleWords,hasSeenSuperTile]);

  useEffect(()=>{if(showSuperTile)setHasSeenSuperTile(true);},[showSuperTile]);

  useEffect(()=>{if(!showSuperTile||!superTileSvgRef.current||FEATURED_PUZZLES.some(word=>!completedBoards[word]))return;setSuperTileImage("");const svg=superTileSvgRef.current,markup=new XMLSerializer().serializeToString(svg),sourceUrl=URL.createObjectURL(new Blob([markup],{type:"image/svg+xml"})),image=new Image();let pngUrl="";image.onload=()=>{const canvas=document.createElement("canvas");canvas.width=1200;canvas.height=1200;const context=canvas.getContext("2d");if(context){context.clearRect(0,0,1200,1200);context.drawImage(image,0,0,1200,1200);canvas.toBlob(blob=>{if(!blob)return;pngUrl=URL.createObjectURL(blob);setSuperTileImage(pngUrl);},"image/png");}URL.revokeObjectURL(sourceUrl);};image.src=sourceUrl;return()=>{URL.revokeObjectURL(sourceUrl);if(pngUrl)URL.revokeObjectURL(pngUrl);};},[showSuperTile,completedBoards,patterns,geometries,bonusPuzzleWords]);

  function getPattern(id:string){return patterns.find(p=>p.id===id)!;}
  function hintHidden(tile:Tile){const targets=new Set(puzzleTemplate.targetSlots.filter(([tileIndex])=>tileIndex===tile.id-1).map(([,region])=>region));return hintMode?Object.fromEntries(geometries[tile.patternId].regions.map(region=>[region.id,!targets.has(region.id)])):{};}
  function regionAtPort(tile:Placed,edge:number,port:number){const geo=geometries[tile.patternId];const localEdge=(edge-tile.rotation+60)%6;return geo.regions.find(r=>r.ports.some(([e,p])=>e===localEdge&&p===port))?.id;}

  const analyze=useCallback((candidate:Preview|null):Analysis=>{
    const temp={...board};if(candidate){const source=hand.find(t=>t.id===candidate.tileId);if(source)temp[candidate.cell]={...source,rotation:candidate.rotation};}
    const parent:Record<string,string>={};const nodes:string[]=[];
    for(const [cell,tile] of Object.entries(temp)){for(const r of geometries[tile.patternId].regions){const n=`${cell}|${r.id}`;parent[n]=n;nodes.push(n);}}
    const find=(x:string):string=>parent[x]===x?x:(parent[x]=find(parent[x]));const union=(a:string,b:string)=>{a=find(a);b=find(b);if(a!==b)parent[b]=a;};
    for(const [cell,tile] of Object.entries(temp)){const [q,r]=cell.split(",").map(Number);for(let e=0;e<6;e++){const nk=keyOf(q+DIRS[e][0],r+DIRS[e][1]),other=temp[nk];if(!other)continue;for(let p=0;p<2;p++){const a=regionAtPort(tile,e,p),b=regionAtPort(other,(e+3)%6,1-p);if(a!==undefined&&b!==undefined)union(`${cell}|${a}`,`${nk}|${b}`);}}}
    const groups=new Map<string,string[]>();for(const n of nodes){const root=find(n),arr=groups.get(root)||[];arr.push(n);groups.set(root,arr);}
    const canCache=new Map<string,boolean>();const comps:Component[]=[];
    for(const ns of groups.values()){let closed=true,dead=false;const letters:string[]=[];let touched=false;for(const node of ns){const [cell,riText]=node.split("|"),ri=+riText,tile=temp[cell],letter=tile.letters[ri];if(letter)letters.push(letter);if(candidate&&cell===candidate.cell)touched=true;const [q,r]=cell.split(",").map(Number),region=geometries[tile.patternId].regions[ri];for(const [le,port] of region.ports){const e=(le+tile.rotation)%6,nk=keyOf(q+DIRS[e][0],r+DIRS[e][1]);if(!temp[nk]){closed=false;if(!boardKeys.has(nk))dead=true;}else if(regionAtPort(temp[nk],(e+3)%6,1-port)===undefined)closed=false;}}
      const sig=signature(letters);let valid=true,possible:string[]=[];if(touched&&!dead){if(closed){if(letters.length===0)valid=true;else{possible=[...(activeThemeBySignature.get(sig)||[]),...(exact.get(sig)||[])];valid=letters.length===1||possible.length>0;}}else if(letters.length===0)valid=true;else{if(canCache.has(sig))valid=canCache.get(sig)!;else{const need:Record<string,number>={};for(const c of letters)need[c]=(need[c]||0)+1;valid=[...words,...activeThemeWords].some(w=>{if(w.length<letters.length)return false;const have:Record<string,number>={};for(const c of w)have[c]=(have[c]||0)+1;return Object.entries(need).every(([c,n])=>(have[c]||0)>=n);});canCache.set(sig,valid);}}}
      comps.push({nodes:ns,letters,closed,dead,touched,valid,words:possible});
    }
    const nodeStatus:Analysis["nodeStatus"]={};for(const c of comps){if(c.dead)for(const n of c.nodes)nodeStatus[n]="dead";else if(c.touched)for(const n of c.nodes)nodeStatus[n]=!c.valid?"invalid":c.closed?"closed":"affected";}
    const touched=comps.filter(c=>c.touched);return {components:comps,nodeStatus,valid:touched.every(c=>c.valid),closed:touched.filter(c=>c.closed)};
  },[board,hand,geometries,exact,words,boardKeys,activeThemeWords,activeThemeBySignature]);
  const restingAnalysis=useMemo(()=>analyze(null),[analyze]);
  const analysis=useMemo(()=>analyze(preview),[analyze,preview]);
  const isRegularWord=(c:Component)=>c.letters.length>1||c.words.length>0;
  const isVoidSingleton=(c:Component)=>c.letters.length===1&&c.words.length===0;
  const closingWords=analysis.closed.filter(isRegularWord);
  const validWordsFor=(letters:string[])=>[...(activeThemeBySignature.get(signature(letters))||[]),...(exact.get(signature(letters))||[])];

  function colorForLength(length:number){if(length===0)return voidColor;if(length===1)return wordColors.one;if(length===2)return wordColors.two;if(length===3)return wordColors.three;if(length===4)return wordColors.four;if(length===5)return wordColors.five;if(length===6)return wordColors.six;return wordColors.sevenPlus;}
  const targetWordColor=TARGET_COLORS[puzzle.word]??colorForLength(puzzle.word.length);
  function visualsFor(cell:string,tile:Tile){const status:Record<number,string>={},fills:Record<number,string>={},hidden:Record<number,boolean>={};geometries[tile.patternId].regions.forEach(r=>{const node=`${cell}|${r.id}`,component=restingAnalysis.components.find(c=>c.nodes.includes(node));hidden[r.id]=false;if(!component)return;if(component.dead){status[r.id]="dead";fills[r.id]=voidColor;}else if(component.closed){const possible=validWordsFor(component.letters),voided=component.letters.length===0||(component.letters.length===1&&!possible.length),isTarget=signature(component.letters)===signature(puzzle.word);status[r.id]=voided?"dead":possible.length?"closed":"invalid";fills[r.id]=voided?voidColor:possible.length?(isTarget?targetWordColor:colorForLength(component.letters.length)):(activeInterfaceTheme.invalid??"#e83f52");}else status[r.id]="affected";});return {status,fills,hidden};}
  function componentsForCompletedBoard(temp:Record<string,Placed>){const parent:Record<string,string>={},nodes:string[]=[];for(const [cell,tile] of Object.entries(temp))for(const region of geometries[tile.patternId].regions){const node=`${cell}|${region.id}`;parent[node]=node;nodes.push(node);}const find=(node:string):string=>parent[node]===node?node:(parent[node]=find(parent[node])),union=(a:string,b:string)=>{a=find(a);b=find(b);if(a!==b)parent[b]=a;};for(const [cell,tile] of Object.entries(temp)){const [q,r]=cell.split(",").map(Number);for(let edge=0;edge<6;edge++){const neighborKey=keyOf(q+DIRS[edge][0],r+DIRS[edge][1]),neighbor=temp[neighborKey];if(!neighbor)continue;for(let port=0;port<2;port++){const a=regionAtPort(tile,edge,port),b=regionAtPort(neighbor,(edge+3)%6,1-port);if(a!==undefined&&b!==undefined)union(`${cell}|${a}`,`${neighborKey}|${b}`);}}}const groups=new Map<string,string[]>();for(const node of nodes){const root=find(node),group=groups.get(root)||[];group.push(node);groups.set(root,group);}return [...groups.values()].map(group=>{let closed=true,dead=false;const letters:string[]=[];for(const node of group){const [cell,regionText]=node.split("|"),regionId=+regionText,tile=temp[cell],[q,r]=cell.split(",").map(Number),region=geometries[tile.patternId].regions[regionId];if(tile.letters[regionId])letters.push(tile.letters[regionId]);for(const [localEdge,port] of region.ports){const edge=(localEdge+tile.rotation)%6,neighborKey=keyOf(q+DIRS[edge][0],r+DIRS[edge][1]);if(!temp[neighborKey]){closed=false;if(!boardKeys.has(neighborKey))dead=true;}else if(regionAtPort(temp[neighborKey],(edge+3)%6,1-port)===undefined)closed=false;}}return {nodes:group,letters,closed,dead,touched:false,valid:true,words:exact.get(signature(letters))||[]} as Component;});}
  function createCompletedSnapshot(index:number,solvedBoard:Record<string,Placed>){const spec=PUZZLES[index],palette=paletteForWord(spec.word),fills:Record<string,Record<number,string>>={},specThemeWords=spec.themeId?[...THEME_WORDS[spec.themeId]]:[];for(const component of componentsForCompletedBoard(solvedBoard)){let fill="";if(component.dead)fill=voidColor;else if(component.closed){const componentSignature=signature(component.letters),possible=[...specThemeWords.filter(word=>signature(word)===componentSignature),...(exact.get(componentSignature)||[])],isTarget=componentSignature===signature(spec.word),voided=component.letters.length===0||(component.letters.length===1&&!possible.length);fill=voided?voidColor:isTarget?palette.targetColor:possible.length?palette.words[colorKeyForLength(component.letters.length)]:(activeInterfaceTheme.invalid??"#e83f52");}if(fill)for(const node of component.nodes){const [cell,region]=node.split("|");(fills[cell]??={})[+region]=fill;}}return {word:spec.word,board:solvedBoard,fills,lineColor:palette.line,tileColor,voidColor,targetColor:palette.targetColor,completedAt:new Date().toISOString()} as CompletedBoardSnapshot;}
  function markBoardChanged(){setConfirmNotice("");if(won){setWon(false);setSubmissionMessage("");setClosedNodes({});}}
  function setCandidate(cell:string,tileId=selectedId,rotation?:number){if(board[cell]||gameOver)return;if(selectedCell){const tile=board[selectedCell];if(!tile)return;markBoardChanged();setBoard(current=>{const next={...current};delete next[selectedCell];next[cell]=tile;return next;});setSelectedCell(cell);setFlash(false);return;}if(tileId===null)return;const tile=hand.find(item=>item.id===tileId);if(!tile)return;markBoardChanged();const placed={...tile,rotation:rotation??tile.rotation};setBoard(current=>({...current,[cell]:placed}));setHand(items=>items.filter(item=>item.id!==tileId));setSelectedId(null);setSelectedCell(cell);setFlash(false);}
  function returnBoardTileToHand(cell:string){const tile=board[cell];if(!tile||gameOver)return;markBoardChanged();setBoard(current=>{const next={...current};delete next[cell];return next;});setHand(items=>items.some(item=>item.id===tile.id)?items:[...items,tile]);setSelectedCell(null);setSelectedId(tile.id);setFlash(false);}
  function moveBoardTile(source:string,destination:string){if(source===destination||board[destination]||gameOver)return;const tile=board[source];if(!tile)return;markBoardChanged();setBoard(current=>{const next={...current};delete next[source];next[destination]=tile;return next;});setSelectedCell(destination);setSelectedId(null);setFlash(false);}
  function beginBoardPointerDrag(e:React.PointerEvent<SVGGElement>,cell:string,tile:Tile){if(gameOver||e.button!==0)return;const startX=e.clientX,startY=e.clientY,sourceSize=(e.currentTarget.querySelector("svg")??e.currentTarget).getBoundingClientRect().width||95;let moved=false;const move=(event:PointerEvent)=>{if(!moved&&Math.hypot(event.clientX-startX,event.clientY-startY)<4)return;moved=true;setDragVisual({tileId:tile.id,x:event.clientX,y:event.clientY,size:sourceSize});};const up=(event:PointerEvent)=>{window.removeEventListener("pointermove",move);window.removeEventListener("pointerup",up);clearDragVisual();if(!moved)return;suppressBoardClickRef.current=true;setTimeout(()=>{suppressBoardClickRef.current=false;},0);const target=document.elementFromPoint(event.clientX,event.clientY);if(target?.closest("[data-hand-drop]"))returnBoardTileToHand(cell);else{const destination=target?.closest("[data-board-cell]")?.getAttribute("data-board-cell");if(destination&&!board[destination])moveBoardTile(cell,destination);}};window.addEventListener("pointermove",move);window.addEventListener("pointerup",up,{once:true});}
  function returnPreviewToHand(){if(!preview)return;setHand(items=>items.map(tile=>tile.id===preview.tileId?{...tile,rotation:preview.rotation}:tile));setPreview(null);}
  function cancelPreview(){if(!preview)return;returnPreviewToHand();dragGhostRef.current?.remove();dragGhostRef.current=null;setDraggingId(null);setDragVisual(null);}
  function selectHandTile(tileId:number){if(preview&&preview.tileId!==tileId)returnPreviewToHand();setSelectedCell(null);setSelectedId(tileId);}
  function beginTileDrag(e:React.DragEvent<Element>,tileId:number,rotation:number){e.dataTransfer.effectAllowed="move";e.dataTransfer.setData("tile",String(tileId));e.dataTransfer.setData("rotation",String(rotation));dropAcceptedRef.current=false;dragGhostRef.current?.remove();const ghost=document.createElement("div");ghost.className="native-drag-ghost";document.body.appendChild(ghost);dragGhostRef.current=ghost;e.dataTransfer.setDragImage(ghost,0,0);const source=(e.currentTarget as Element).querySelector("svg")??e.currentTarget,size=source.getBoundingClientRect().width||95;setDragVisual({tileId,x:e.clientX,y:e.clientY,size});}
  function clearDragVisual(){dragGhostRef.current?.remove();dragGhostRef.current=null;setDraggingId(null);setDragVisual(null);}
  function finishTileDrag(fromPreview=false){clearDragVisual();if(!dropAcceptedRef.current&&fromPreview)cancelPreview();}
  useEffect(()=>{if(!dragVisual)return;const move=(e:DragEvent)=>{const boardRect=boardSvgRef.current?.getBoundingClientRect(),viewBox=boardSvgRef.current?.viewBox.baseVal,onBoard=Boolean(boardRect&&e.clientX>=boardRect.left&&e.clientX<=boardRect.right&&e.clientY>=boardRect.top&&e.clientY<=boardRect.bottom),boardSize=boardRect&&viewBox?.width&&viewBox?.height?Math.min(boardRect.width/viewBox.width,boardRect.height/viewBox.height)*100:72;setDragVisual(current=>current&&({...current,x:e.clientX,y:e.clientY,size:onBoard?boardSize:95}));};window.addEventListener("dragover",move);return()=>window.removeEventListener("dragover",move);},[Boolean(dragVisual)]);
  function finishGame(baseBoard=board,remainingHand=hand,remainingDeck=deck){const finalBoard={...baseBoard},empty=cells.filter(({q,r})=>!finalBoard[keyOf(q,r)]),available=shuffle([...remainingHand,...remainingDeck]);let nextId=Math.max(0,...Object.values(finalBoard).map(tile=>tile.id),...available.map(tile=>tile.id))+1;for(const cell of empty){const source=available.shift(),pattern=source?getPattern(source.patternId):patterns[Math.floor(Math.random()*patterns.length)];finalBoard[keyOf(cell.q,cell.r)]={id:source?.id??nextId++,patternId:pattern.id,rotation:source?.rotation??Math.floor(Math.random()*6),letters:geometries[pattern.id].regions.map(()=>"")};}setBoard(finalBoard);setClosedNodes(old=>{const next={...old};for(const [cell,tile] of Object.entries(finalBoard))for(const region of geometries[tile.patternId].regions){const node=`${cell}|${region.id}`;if(next[node]===undefined)next[node]=0;}return next;});setDestroyedCount(count=>count+available.length);setDeck([]);setHand([]);setHandSlots({});setPreview(null);setPending(null);setEntries([]);setSelectedId(null);setNewId(null);clearDragVisual();setGameOver(true);}
  function commit(wordsChosen:string[]=[]){if(!preview)return;const tile=hand.find(t=>t.id===preview.tileId);if(!tile)return;const placed={...tile,rotation:preview.rotation},nextBoard={...board,[preview.cell]:placed},remaining=hand.filter(t=>t.id!==tile.id),solved=wordsChosen.includes(puzzle.word);setBoard(nextBoard);setHand(remaining);const wordClosures=analysis.closed.filter(isRegularWord),voidSingletons=analysis.closed.filter(isVoidSingleton),wordPoints=wordClosures.map(c=>c.nodes.length*Math.max(0,c.letters.length-1)),gained=wordPoints.reduce((a,b)=>a+b,0)-voidSingletons.length*5;setScore(s=>s+gained);if(analysis.closed.length)setClosedNodes(old=>{const next={...old};analysis.closed.forEach(c=>c.nodes.forEach(node=>next[node]=isVoidSingleton(c)?0:c.letters.length));return next;});setHistory(h=>[...h,{turn,words:wordsChosen,wordPoints,points:gained}]);setTurn(t=>t+1);setPreview(null);setPending(null);setEntries([]);setHandSlots(slots=>{const updated={...slots};delete updated[tile.id];return updated;});setSelectedId(remaining[0]?.id??null);if(solved){setWon(true);setGameOver(true);}else if(!remaining.length)setGameOver(true);}
  function drawNext(remaining:Tile[],slot:number,removedId:number){if(deck.length){const [next,...rest]=deck;setDeck(rest);setHand([...remaining,next]);setHandSlots(slots=>{const updated={...slots};delete updated[removedId];updated[next.id]=slot;return updated;});setNewId(next.id);setSelectedId(next.id);}else{setHandSlots(slots=>{const updated={...slots};delete updated[removedId];return updated;});setNewId(null);setSelectedId(remaining[0]?.id??null);if(!remaining.length)setGameOver(true);}}
  function confirm(){if(!preview)return;if(!analysis.valid){setFlash(true);setTimeout(()=>setFlash(false),1300);return;}const wordClosures=analysis.closed.filter(isRegularWord);if(wordClosures.length){if(chooseWord){commit(wordClosures.map(c=>c.words[Math.floor(Math.random()*c.words.length)]));return;}const initial=wordClosures.map(c=>c.words.length===1?c.words[0]:"");if(initial.every(Boolean))commit(initial);else{setPending(wordClosures);setEntries(initial);}}else commit();}
  function submitWords(){if(!pending)return;const ok=pending.every((c,i)=>(exact.get(signature(c.letters))||[]).includes(entries[i].trim().toUpperCase()));if(!ok){setFlash(true);setTimeout(()=>setFlash(false),1300);return;}commit(entries.map(x=>x.trim().toUpperCase()));}
  function tradeTile(){if(selectedId===null||!deck.length)return;const slot=handSlots[selectedId],[next,...rest]=deck;setDeck(rest);setHand([...hand.filter(tile=>tile.id!==selectedId),next]);setHandSlots(slots=>{const updated={...slots};delete updated[selectedId];updated[next.id]=slot;return updated;});setDestroyedCount(count=>count+1);setNewId(next.id);setSelectedId(next.id);setPreview(null);setTurn(t=>t+1);}
  function rotateSelected(delta:number){if(gameOver)return;if(selectedCell){markBoardChanged();setBoard(current=>({...current,[selectedCell]:{...current[selectedCell],rotation:(current[selectedCell].rotation+delta+6)%6}}));}else if(selectedId!==null){markBoardChanged();setHand(items=>items.map(tile=>tile.id===selectedId?{...tile,rotation:(tile.rotation+delta+6)%6}:tile));}}
  function boardWords(components:Component[]){const found:string[]=[];for(const component of components){if(!component.closed||component.letters.length<2)continue;const componentSignature=signature(component.letters),isTarget=componentSignature===signature(puzzle.word),possible=validWordsFor(component.letters);if(!isTarget&&!possible.length)continue;const matches=isTarget?[puzzle.word]:possible;for(const word of matches)if(!found.includes(word))found.push(word);}return found;}
  function rememberWords(found:string[]){if(!found.length)return;const themed=found.some(word=>activeThemeWords.includes(word)&&word!==puzzle.word);if(themed)setBonusPuzzleWords(current=>new Set(current).add(puzzle.word));const now=new Date().toISOString();setDiscoveredWords(current=>{const seen=new Set(current.map(item=>item.word)),additions=found.filter(word=>!seen.has(word)).map(word=>({word,puzzle:puzzle.word,foundAt:now,themed:word!==puzzle.word&&activeThemeWords.includes(word)}));return [...additions,...current];});}
  function confirmPuzzle(){if(Object.keys(board).length!==cells.length)return;const targetSignature=signature(puzzle.word),target=restingAnalysis.components.find(component=>component.closed&&signature(component.letters)===targetSignature),invalidClosed=restingAnalysis.components.some(component=>component.closed&&component.letters.length>1&&signature(component.letters)!==targetSignature&&!validWordsFor(component.letters).length);if(invalidClosed){setSubmissionMessage("");setConfirmNotice("");setFlash(true);setTimeout(()=>setFlash(false),1300);return;}const found=boardWords(restingAnalysis.components),newThemeForBoard=!bonusPuzzleWords.has(puzzle.word)&&found.some(word=>activeThemeWords.includes(word)&&word!==puzzle.word),knownWords=new Set(discoveredWords.map(item=>item.word)),hasNewWords=found.some(word=>!knownWords.has(word));rememberWords(found);if(!target){setSubmissionMessage(found.length?`Valid board — added ${found.join(" · ")}.`:"Valid board — no closed words to add yet.");if(newThemeForBoard)showConfirmNotice("New theme word!");else if(hasNewWords)showConfirmNotice("New words found!");return;}const points=target.nodes.length*Math.max(0,puzzle.word.length-1),snapshot=createCompletedSnapshot(activePuzzle,board);setSubmissionMessage("");setConfirmNotice("");setWon(true);setGameOver(false);setCompletedWords(done=>new Set(done).add(puzzle.word));setCompletedBoards(done=>{const next={...done,[puzzle.word]:snapshot};if(!TUTORIAL_MODE&&FEATURED_PUZZLES.every(word=>next[word]))setShowSuperTile(true);return next;});setScore(points);setHistory([{turn:1,words:found,wordPoints:found.map(word=>word===puzzle.word?points:0),points}]);setClosedNodes(Object.fromEntries(target.nodes.map(node=>[node,puzzle.word.length])));setSelectedCell(null);setSelectedId(null);}
  useEffect(()=>{const key=(e:KeyboardEvent)=>{if(pending)return;if(e.key.toLowerCase()==="r")rotateSelected(1);if(e.key.toLowerCase()==="q")rotateSelected(-1);if(e.key==="Enter"&&Object.keys(board).length===cells.length){e.preventDefault();confirmPuzzle();}if((e.key==="Escape"||e.key==="Delete"||e.key==="Backspace")&&selectedCell){e.preventDefault();returnBoardTileToHand(selectedCell);}};window.addEventListener("keydown",key);return()=>window.removeEventListener("keydown",key);},[pending,selectedCell,selectedId,board,restingAnalysis,cells.length,gameOver]);

  const displayBoard=preview?{...board,[preview.cell]:{...hand.find(t=>t.id===preview.tileId)!,rotation:preview.rotation}}:board;
  const selected=hand.find(t=>t.id===selectedId);
  const totalWeight=patterns.reduce((n,p)=>n+p.weight,0);
  const coversEveryEdge=(pattern:Pattern)=>new Set(pattern.pairs.flat()).size===6;
  const configValid=configLoaded&&dictionaryLoaded&&patterns.length>0&&totalWeight===100&&patterns.every(coversEveryEdge);
  function addGeometry(){const number=patterns.length+1;setPatterns(ps=>[...ps,{id:`geometry-${Date.now()}`,label:`Geometry ${number}`,pairs:[[1,2],[3,4],[5,6]],weight:0}]);setConfigDirty(true);}
  function applyTheme(id:string){const theme=THEMES.find(item=>item.id===id);if(!theme)return;setThemeId(id);setSurfaceColor(theme.surface);setPanelColor(theme.panel);setTileColor(theme.tile);setLineColor(theme.line);setAccentColor(theme.accent);setVoidColor(theme.void);setWordColors(theme.words);}
  function nextPuzzle(){const current=FEATURED_PUZZLES.indexOf(puzzle.word),ordered=FEATURED_PUZZLES.map((_,offset)=>FEATURED_PUZZLES[(Math.max(current,0)+1+offset)%FEATURED_PUZZLES.length]),next=ordered.find(word=>!completedWords.has(word))??ordered[0];if(TUTORIAL_MODE&&current===FEATURED_PUZZLES.length-1){window.location.href="../puzzle/";return;}const index=featuredPuzzleIndex(next);if(index>=0)startPuzzle(index);}
  function solutionBoardFor(index:number){const template=PUZZLE_TEMPLATES[PUZZLES[index].template],tiles=createPuzzleTiles(index).map((tile,tileIndex)=>({...tile,rotation:template.solutionRotations[tileIndex]}));return Object.fromEntries(SOLUTION_CELL_KEYS.map((cell,tileIndex)=>[cell,tiles[tileIndex]]));}
  function finishSix(){const words=FEATURED_PUZZLES.slice(0,6),snapshots:Record<string,CompletedBoardSnapshot>={};for(const word of words){const index=featuredPuzzleIndex(word),solvedBoard=solutionBoardFor(index);snapshots[word]=createCompletedSnapshot(index,solvedBoard);}setCompletedBoards(snapshots);setCompletedWords(new Set(words));const remainingIndex=featuredPuzzleIndex(FEATURED_PUZZLES[6]);startPuzzle(remainingIndex);}
  function clearSavedProgress(){if(!window.confirm("Clear all saved progress?"))return;localStorage.removeItem(STORAGE_KEY);setCompletedWords(new Set());setCompletedBoards({});setDiscoveredWords([]);setBonusPuzzleWords(new Set());setHasSeenSuperTile(false);setShowSuperTile(false);setSuperTileImage("");startPuzzle(activePuzzle);}
  function confirmNewGame(){if(gameOver||window.confirm("Reset the current game?"))newGame();}
  const foundWords=[...discoveredWords].sort((a,b)=>Number(Boolean(b.themed))-Number(Boolean(a.themed))||b.foundAt.localeCompare(a.foundAt));
  const activeInterfaceTheme=THEMES.find(theme=>theme.id===themeId)??DEFAULT_THEME;
  const nextButtonLabel=TUTORIAL_MODE&&FEATURED_PUZZLES.indexOf(puzzle.word)===FEATURED_PUZZLES.length-1?"Start puzzles":TUTORIAL_MODE?"Next lesson":"Next Puzzle";
  const handBySlot=Object.fromEntries(hand.map(tile=>[handSlots[tile.id],tile])) as Record<number,Tile>;
  const boardRadius=boardSide-1,viewWidth=boardRadius*159.4+140,viewHeight=boardRadius*138+140,targetTileSize=({2:120,3:100,4:82,5:68,6:58} as Record<number,number>)[boardSide]??82,boardDisplayWidth=viewWidth*targetTileSize/100;
  const palette=([{key:"one",label:"1"},{key:"two",label:"2"},{key:"three",label:"3"},{key:"four",label:"4"},{key:"five",label:"5"},{key:"six",label:"6"},{key:"sevenPlus",label:"7+"}] as {key:keyof WordColors;label:string}[]);
  function saveFinishedBoard(){if(!boardSvgRef.current)return;const svg=boardSvgRef.current.cloneNode(true) as SVGSVGElement,ns="http://www.w3.org/2000/svg";svg.setAttribute("xmlns",ns);svg.setAttribute("width","1200");svg.setAttribute("height","1200");svg.classList.remove("flash");const style=document.createElementNS(ns,"style");style.textContent=`.tile-paper{fill:${tileColor};stroke:#20251f;stroke-width:1.25}.wall{fill:none;stroke:${lineColor};stroke-width:4.5;stroke-linecap:round}.region-fill{fill:${voidColor}}.region-fill.complete{fill:${voidColor}}.empty-hex{fill:${voidColor};stroke:#20251f;stroke-width:1.25}.letter{font:900 12px Arial;text-anchor:middle;fill:#20251f;paint-order:stroke;stroke:${tileColor};stroke-width:2.5px}.cell{cursor:default}`;svg.prepend(style);const longest=[...foundWords].sort((a,b)=>b.word.length-a.word.length)[0]?.word;if(longest){const label=document.createElementNS(ns,"text");label.setAttribute("x","350");label.setAttribute("y","350");label.setAttribute("text-anchor","middle");label.setAttribute("dominant-baseline","middle");label.setAttribute("fill","#20251f");label.setAttribute("stroke",tileColor);label.setAttribute("stroke-width","5");label.setAttribute("paint-order","stroke");label.setAttribute("font-family","Georgia, serif");label.setAttribute("font-size",String(Math.max(24,Math.min(64,250/longest.length))));label.setAttribute("font-weight","700");label.textContent=longest;svg.append(label);}const blob=new Blob([new XMLSerializer().serializeToString(svg)],{type:"image/svg+xml"}),url=URL.createObjectURL(blob),link=document.createElement("a");link.href=url;link.download=`tiled-board-${new Date().toISOString().slice(0,10)}.svg`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}

  return <main className={TUTORIAL_MODE?"tutorial-mode":undefined} style={{"--tile-line":lineColor,"--green":lineColor,"--void":voidColor,"--white":tileColor,"--paper":surfaceColor,"--panel":panelColor,"--orange":accentColor,"--ink":activeInterfaceTheme.ink??"#20251f","--muted":activeInterfaceTheme.muted??"#71766d","--line":activeInterfaceTheme.border??"#cbc5b7","--bad":activeInterfaceTheme.invalid??"#e55348","--pale":activeInterfaceTheme.affected??"#dcebdc","--bright":wordColors.three,"--theme-word":activeInterfaceTheme.themeWord??"#ffe36a","--backdrop":activeInterfaceTheme.backdrop??"rgba(25,29,24,.52)",background:surfaceColor,color:activeInterfaceTheme.ink??"#20251f"} as CSSProperties}>
    {internal&&<header><div><p className="kicker">SOLO PLAYTEST / PROTOTYPE 01</p><h1>Tilde</h1></div><nav><button className={tab==="play"?"active":""} disabled={configDirty} title={configDirty?"Generate a new game to apply your config changes":""} onClick={()=>setTab("play")}>Play</button><button className={tab==="lab"?"active":""} onClick={()=>setTab("lab")}>Game Config</button></nav><button className="new-game" disabled={!configValid} onClick={newGame}>New game</button></header>}
    {tab==="lab"?<section className="puzzle-picker"><div className="puzzle-picker-heading"><div><p className="step">PUZZLE LIBRARY</p><h2>Choose a word.</h2><p>Each hand has at least one verified arrangement that closes its title word.</p></div><div className="puzzle-picker-actions"><button onClick={finishSix}>Finish six</button><button className="clear-progress" onClick={clearSavedProgress}>Clear saved progress</button><button onClick={()=>setTab("play")}>Back to puzzle</button></div></div>{(["easy","medium","hard"] as Difficulty[]).map(tier=><section key={tier}><div><h3>{tier}</h3><span>{tier==="easy"?"More repeated clues · fewer decoys":tier==="medium"?"Some repeated clues · moderate decoys":"Less repetition · dense decoys"}</span></div><div className="puzzle-grid">{PUZZLES.map((item,index)=>item.tier===tier?<button key={item.word} className={`${activePuzzle===index?"active":""} ${completedWords.has(item.word)?"complete":""}`} onClick={()=>selectPuzzle(index)}><b>{item.word}{completedWords.has(item.word)&&<i aria-label="Complete">✓</i>}</b><small>{item.word.length} letters</small></button>:null)}</div></section>)}</section>:<div className={`game-layout ${internal?"internal-layout":"public-layout"}`}>
      <aside className="left-rail" data-hand-drop onDragOver={e=>{if(e.dataTransfer.types.includes("board-cell"))e.preventDefault();}} onDrop={e=>{const source=e.dataTransfer.getData("board-cell");if(source){e.preventDefault();returnBoardTileToHand(source);clearDragVisual();}}}><section className="score-card"><span>PUZZLE</span><strong>{won?"✓":puzzle.word}</strong></section><section className="side-hand"><div className="tray-title"><p className="rail-label">YOUR TILES</p></div><div className="hand-cards">{Array.from({length:handSlotCount},(_,slot)=>{const tile=handBySlot[slot];if(!tile)return <span className="hand-slot-empty" key={`slot-${slot}`}/>;const p=getPattern(tile.patternId);return <button key={tile.id} draggable={!gameOver} onDragStart={e=>{selectHandTile(tile.id);beginTileDrag(e,tile.id,tile.rotation);setDraggingId(tile.id);}} onDragEnd={()=>finishTileDrag()} onClick={()=>!gameOver&&selectHandTile(tile.id)} className={`hand-tile ${selectedId===tile.id?"selected":""} ${draggingId===tile.id?"dragging":""}`}><TileFace tile={tile} pattern={p} geometry={geometries[p.id]} hidden={hintHidden(tile)}/></button>})}</div><div className="hand-actions"><button className={`end-game ${gameOver?"restart":""}`} onClick={newGame}>{gameOver?"Play again":"Restart puzzle"}</button></div></section></aside>
      <section className="board-stage">{internal?<div className="stage-top"><div><p className="step">TURN {String(turn).padStart(2,"0")}</p><h2>{gameOver?"Game complete":preview?"Check the sections":"Place one tile"}</h2></div></div>:<div className="board-tools"><strong className="mobile-puzzle-title">Tilde</strong>{!TUTORIAL_MODE&&hasSeenSuperTile&&FEATURED_PUZZLES.every(word=>completedBoards[word])&&<button className="supertile-crown" aria-label="View your supertile" title="View your supertile" onClick={()=>setShowSuperTile(true)}>♛</button>}<button className="mobile-only mobile-puzzle-button" onClick={()=>setShowPuzzleSelector(true)}>Puzzles</button><button className="mobile-only mobile-puzzle-button" onClick={() => setShowFoundWords(true)}>Words</button>{!TUTORIAL_MODE&&won&&<button className="save-board" onClick={saveFinishedBoard}>Save tiled board SVG</button>}<button aria-label="How to play" title="How to play" onClick={()=>setShowInstructions(true)}>?</button><button aria-label="Restart puzzle" title="Restart puzzle" onClick={confirmNewGame}>↻</button></div>}
      {TUTORIAL_MODE&&puzzle.lesson&&<div className="tutorial-lesson"><b>{puzzle.word} · {puzzle.lesson}</b><span>{puzzle.lessonText}</span></div>}
      <svg ref={boardSvgRef} className={`board ${flash?"flash":""}`} style={{width:`min(100%, ${boardDisplayWidth}px)`}} viewBox={`${350-viewWidth/2} ${350-viewHeight/2} ${viewWidth} ${viewHeight}`} onDragOver={e=>e.preventDefault()}>
        {cells.map(({q,r})=>{
          const cell=keyOf(q,r),x=350+79.7*(q+r/2),y=350+69*r,tile=displayBoard[cell],visual=tile?visualsFor(cell,tile):null;
          const selectCell=()=>{if(suppressBoardClickRef.current)return;if(tile){setSelectedCell(cell);setSelectedId(null);}else setCandidate(cell);};
          return <g key={cell} data-board-cell={cell} transform={`translate(${x-50} ${y-50})`} className={`cell ${tile?"filled":"available"} ${selectedCell===cell?"puzzle-selected":""}`} onPointerDown={e=>{if(tile)beginBoardPointerDrag(e,cell,tile);}} onClick={selectCell} onDragOver={e=>{if(!tile){e.preventDefault();e.dataTransfer.dropEffect="move";}}} onDrop={e=>{e.preventDefault();clearDragVisual();const rotation=Number(e.dataTransfer.getData("rotation"));setCandidate(cell,+e.dataTransfer.getData("tile"),Number.isFinite(rotation)?rotation:undefined);}}>{tile?<TileFace tile={tile} pattern={getPattern(tile.patternId)} geometry={geometries[tile.patternId]} status={visual!.status} fills={visual!.fills} hidden={hintHidden(tile)}/>:<svg width="100" height="100" viewBox="0 0 100 100"><polygon points={HEX.map(p=>p.join(",")).join(" ")} className="empty-hex"/></svg>}</g>;
        })}
        {selectedCell&&displayBoard[selectedCell]&&(()=>{const [q,r]=selectedCell.split(",").map(Number),x=350+79.7*(q+r/2),y=350+69*r;return <polygon className="selected-tile-outline" points={HEX.map(([px,py])=>`${px+x-50},${py+y-50}`).join(" ")}/>})()}
      </svg>
      {!gameOver&&<div className="mobile-tile-controls"><button aria-label="Rotate selected tile left" disabled={!selectedCell&&selectedId===null} onClick={()=>rotateSelected(-1)}><RotateIcon direction="left"/></button><button aria-label="Return selected tile to hand" disabled={!selectedCell} onClick={()=>selectedCell&&returnBoardTileToHand(selectedCell)}><HomeIcon/></button><button aria-label="Rotate selected tile right" disabled={!selectedCell&&selectedId===null} onClick={()=>rotateSelected(1)}><RotateIcon direction="right"/></button></div>}
      <strong className="mobile-target-word">{puzzle.word}</strong>
      <div className={`mobile-confirm-action ${won?"won":""} ${confirmNotice?"notice":""} ${confirmNotice==="New theme word!"?"theme-notice":""} ${flash?"error":""}`}>{won?<button className="primary" onClick={nextPuzzle}>{nextButtonLabel}</button>:<button className="primary" aria-label={confirmNotice||"Confirm puzzle"} disabled={Object.keys(board).length!==cells.length} onClick={confirmPuzzle}>{confirmNotice||"✓"}</button>}</div>
      {!gameOver&&<div className={`confirm-bar puzzle-confirm ${flash?"shake":""}`}><div><span>{won?"Puzzle complete.":flash?"That arrangement closes a section that cannot make a word.":submissionMessage||Object.keys(board).length===cells.length?submissionMessage||"All seven tiles are placed.":`${Object.keys(board).length} of ${cells.length} tiles placed`}</span><small>{won?"You can keep exploring this board or continue to the next puzzle.":"Select any tile to rotate it. Drag board tiles to move them or return them to your hand."}</small></div><button disabled={!selectedCell&&selectedId===null} onClick={()=>rotateSelected(-1)}>Q ↺</button><button disabled={!selectedCell&&selectedId===null} onClick={()=>rotateSelected(1)}>R ↻</button>{won?<button className="primary" onClick={nextPuzzle}>{nextButtonLabel}</button>:<button className="primary" disabled={Object.keys(board).length!==cells.length} onClick={confirmPuzzle}>Confirm puzzle</button>}</div>}
      </section>
      {internal?<aside className="right-rail"><section className="theme-panel"><p className="rail-label">VISUAL THEME</p><select value={themeId} onChange={e=>applyTheme(e.target.value)}>{THEMES.map(theme=><option key={theme.id} value={theme.id}>{theme.name}</option>)}</select><p>Inspired palettes; adjust any color below.</p></section><section className="play-palette"><p className="rail-label">COLORS</p><div><label><input type="color" value={tileColor} onChange={e=>setTileColor(e.target.value)}/>Tile</label><label><input type="color" value={surfaceColor} onChange={e=>setSurfaceColor(e.target.value)}/>Ground</label><label><input type="color" value={panelColor} onChange={e=>setPanelColor(e.target.value)}/>Panel</label><label><input type="color" value={lineColor} onChange={e=>setLineColor(e.target.value)}/>Line</label><label><input type="color" value={accentColor} onChange={e=>setAccentColor(e.target.value)}/>Accent</label><label><input type="color" value={voidColor} onChange={e=>setVoidColor(e.target.value)}/>Void</label>{palette.map(item=><label key={item.key}><input type="color" value={wordColors[item.key]} onChange={e=>setWordColors(colors=>({...colors,[item.key]:e.target.value}))}/>{item.label}</label>)}</div></section></aside>:<aside className="found-panel"><section className="featured-puzzles"><div><p className="rail-label">PUZZLES</p><span>{FEATURED_PUZZLES.filter(word=>completedBoards[word]).length} completed</span></div><div className="featured-grid">{FEATURED_PUZZLES.map(word=>{const index=featuredPuzzleIndex(word),snapshot=completedBoards[word];return <button key={word} className={`${activePuzzle===index?"active":""} ${snapshot?"complete":""}`} onClick={()=>selectPuzzle(index)}><span>{word}{snapshot&&bonusPuzzleWords.has(word)&&<i className="puzzle-bonus-star" aria-label="Theme word found">★</i>}</span>{snapshot&&<BoardThumbnail snapshot={snapshot} patterns={patterns} geometries={geometries} hasBonus={bonusPuzzleWords.has(word)}/>}</button>;})}</div>{!TUTORIAL_MODE&&FEATURED_PUZZLES.every(word=>completedBoards[word])&&<button className="view-super-tile" onClick={()=>setShowSuperTile(true)}>View super tile</button>}</section><section className="found-words-section"><div className="found-header"><p className="rail-label">FOUND WORDS</p><span>{foundWords.length} found</span></div><div className="found-list">{foundWords.length?foundWords.map(item=><b key={item.word} className={item.themed?"themed-word":""} style={{borderColor:colorForLength(item.word.length)}} title={`Found while playing ${item.puzzle}`}>{item.themed?`★ ${item.word}`:item.word}</b>):<p>No words yet.</p>}</div></section></aside>}
      {internal&&<section className="word-tray"><div><p className="rail-label">FOUND WORDS</p><span>{foundWords.length} found</span></div><div className="bottom-words">{foundWords.length?foundWords.map(item=><b key={item.word} className={item.themed?"themed-word":""} style={{borderColor:colorForLength(item.word.length)}}>{item.themed?`★ ${item.word}`:item.word}</b>):<p>No words yet.</p>}</div></section>}
    </div>}
    {showPuzzleSelector&&<div className="modal-backdrop mobile-puzzle-backdrop"><div className="mobile-puzzle-modal"><button className="modal-close" aria-label="Close puzzle list" onClick={()=>setShowPuzzleSelector(false)}>×</button><p className="step">PUZZLES</p><h2>Choose a puzzle</h2><div className="mobile-puzzle-list">{FEATURED_PUZZLES.map(word=>{const index=featuredPuzzleIndex(word),snapshot=completedBoards[word];return <button key={word} className={`${activePuzzle===index?"active":""} ${snapshot?"complete":""}`} onClick={()=>{selectPuzzle(index);setShowPuzzleSelector(false);}}><span>{word}{snapshot&&bonusPuzzleWords.has(word)&&<i className="puzzle-bonus-star" aria-label="Theme word found">★</i>}</span>{snapshot&&<BoardThumbnail snapshot={snapshot} patterns={patterns} geometries={geometries} hasBonus={bonusPuzzleWords.has(word)}/>}</button>;})}</div>{!TUTORIAL_MODE&&FEATURED_PUZZLES.every(word=>completedBoards[word])&&<button className="view-super-tile" onClick={()=>{setShowPuzzleSelector(false);setShowSuperTile(true);}}>View super tile</button>}<button className="mobile-clear-progress" onClick={()=>{clearSavedProgress();setShowPuzzleSelector(false);}}>Clear saved progress</button></div></div>}
    {showFoundWords&&<div className="modal-backdrop mobile-words-backdrop"><div className="mobile-words-modal"><button className="modal-close" aria-label="Close found words" onClick={()=>setShowFoundWords(false)}>×</button><p className="step">FOUND WORDS</p><h2>Your collection</h2><div className="found-list">{foundWords.length?foundWords.map(item=><b key={item.word} className={item.themed?"themed-word":""} style={{borderColor:colorForLength(item.word.length)}}>{item.themed?`★ ${item.word}`:item.word}</b>):<p>No words yet.</p>}</div></div></div>}
    {!TUTORIAL_MODE&&showSuperTile&&FEATURED_PUZZLES.every(word=>completedBoards[word])&&<div className="modal-backdrop"><div className="super-tile-modal"><button className="modal-close" aria-label="Close supertile" onClick={()=>setShowSuperTile(false)}>×</button><div className="super-tile-rays"><div className="super-tile">{superTileImage?<img src={superTileImage} alt="Your seven completed puzzle boards tiled into one supertile" draggable="false"/>:<span>Building your supertile…</span>}</div></div><p className="super-tile-message"><strong>Well done!</strong> The next puzzle set arrives 7/27/26</p><button className="primary" onClick={()=>setShowSuperTile(false)}>Close</button><SupertileSvg snapshots={FEATURED_PUZZLES.map(word=>completedBoards[word])} patterns={patterns} geometries={geometries} svgRef={superTileSvgRef} bonusPuzzleWords={bonusPuzzleWords}/></div></div>}
    {showInstructions&&<div className="modal-backdrop"><div className="instructions-modal"><button className="modal-close" aria-label="Close instructions" onClick={()=>setShowInstructions(false)}>×</button>{!TUTORIAL_MODE&&<a className="tutorial-link tutorial-link-top" href="../how/">Play the tutorial →</a>}<p className="step instructions-step">HOW TO PLAY</p><div className="instructions-copy"><p>Arrange all seven tiles anywhere on the board by tapping to select and again to place them. Use the arrow buttons to rotate a selected tile.</p><p>Close the letters of the puzzle title together in any order to complete the puzzle.</p><p>All other closed spaces must contain a word, a single letter, or nothing.</p><p>When all seven tiles are placed, use the checkmark to collect your words.</p></div>{!TUTORIAL_MODE&&<p className="instructions-bonus"><b>Found every target word? Keep going!</b> More theme words are hidden across the puzzles—at least one in each. Find them to jazz up your supertile.</p>}<button className="primary" onClick={()=>setShowInstructions(false)}>Got it</button>{TUTORIAL_MODE&&<a className="quiet tutorial-exit" href="../puzzle/">Skip to the puzzles</a>}</div></div>}
    {pending&&<div className="modal-backdrop"><div className={`word-modal ${flash?"shake":""}`}><p className="step">CLOSED SECTION{pending.filter(c=>c.words.length!==1).length>1?"S":""}</p><h2>Name the word{pending.filter(c=>c.words.length!==1).length>1?"s":""}.</h2>{pending.map((c,i)=>c.words.length===1?null:<div className="word-entry" key={i}><div className="letters">{c.letters.map((l,j)=><span key={j}>{l}</span>)}</div>{finder&&<p className="hints">Possible: {c.words.slice(0,8).join(" · ")}</p>}<input autoFocus={entries.findIndex((_,j)=>pending[j].words.length!==1)===i} value={entries[i]} onChange={e=>setEntries(x=>x.map((v,j)=>j===i?e.target.value.toUpperCase():v))} onKeyDown={e=>{if(e.key==="Enter")submitWords();}} placeholder="Type a valid anagram"/></div>)}<div className="modal-actions"><button className="quiet" onClick={()=>setPending(null)}>Back to placement</button><button className="primary" onClick={submitWords}>Submit & score</button></div></div></div>}
    {dragVisual&&(()=>{const tile=hand.find(item=>item.id===dragVisual.tileId)??Object.values(board).find(item=>item.id===dragVisual.tileId),pattern=tile&&getPattern(tile.patternId);return tile&&pattern?<div className="tile-drag-follow" style={{left:dragVisual.x,top:dragVisual.y,width:dragVisual.size,height:dragVisual.size}}><TileFace tile={tile} pattern={pattern} geometry={geometries[pattern.id]} hidden={hintHidden(tile)}/></div>:null;})()}
  </main>;
}
